#head;hrl;2.0;utf-8
                   #ref#speechfile#speaker#gender#reference word sequence#topic#;slot names#;slot values
                   head
ref#Tun01023010.pcm#lixiyong#male#打开收音机#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023011.pcm#lixiyong#male#打开电台#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023012.pcm#lixiyong#male#播放电台#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023013.pcm#lixiyong#male#我想打开收音机#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023015.pcm#lixiyong#male#我要启动收音机#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023016.pcm#lixiyong#male#我想打开电台#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023017.pcm#lixiyong#male#我想收听电台#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023018.pcm#lixiyong#male#切换到收音机#INTENT_Ent_Radio_PlayRadio##
ref#Tun01023019.pcm#lixiyong#male#我要切到电台#INTENT_Ent_Radio_PlayRadio##
ref#Ecarx_Tuner_7511107_.pcm#Wangxu#male#打开收音机#INTENT_Ent_Radio_PlayRadio##
ref#0002_wangxu_male.pcm#Wangxu#male#播放收音机#INTENT_Ent_Radio_PlayRadio##
ref#0003_wangxu_male.pcm#Wangxu#male#我要听收音机#INTENT_Ent_Radio_PlayRadio##
ref#0003_tongchunhua_female.pcm#tongchunhua#female#我要听收音机#INTENT_Ent_Radio_PlayRadio##
ref#0005_wangxu_male.pcm#Wangxu#male#开收音机#INTENT_Ent_Radio_PlayRadio##
ref#0006_wangxu_male.pcm#Wangxu#male#切换到收音机#INTENT_Ent_Radio_PlayRadio##
ref#0007_wangxu_male.pcm#Wangxu#male#进入收音机#INTENT_Ent_Radio_PlayRadio##
ref#0008_wangxu_male.pcm#Wangxu#male#打开广播#INTENT_Ent_Radio_PlayRadio##
ref#0009_wangxu_male.pcm#Wangxu#male#播放广播#INTENT_Ent_Radio_PlayRadio##
ref#0010_tongchunhua_female.pcm#Tongchunhua#female#我要听广播#INTENT_Ent_Radio_PlayRadio##
ref#0011_tongchunhua_female.pcm#Tongchunhua#female#我想听广播#INTENT_Ent_Radio_PlayRadio##
ref#0012_wangxu_male.pcm#Wangxu#male#开广播#INTENT_Ent_Radio_PlayRadio##
ref#0013_wangxu_male.pcm#Wangxu#male#切换到广播#INTENT_Ent_Radio_PlayRadio##
ref#0014_wangxu_male.pcm#Wangxu#male#进入广播#INTENT_Ent_Radio_PlayRadio##
ref#0015_wangxu_male.pcm#Wangxu#male#打开电台#INTENT_Ent_Radio_PlayRadio##
