# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrt_project',
            name='creater',
            field=models.CharField(default='admin', max_length=255, verbose_name='creater'),
        ),
    ]
