# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180119_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrt_testsuit',
            name='testsuit_name',
            field=models.CharField(max_length=255, verbose_name='testsuit_name'),
        ),
    ]
