#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#;slot names#;slot values
head
ref#Vehicle_01001.pcm#zlb#male#把车窗打开#INTENT_VEH_OpenWindow##
ref#Vehicle_01002.pcm#zlb#male#开启车窗#INTENT_VEH_OpenWindow##
ref#Vehicle_01003.pcm#zlb#male#打开车窗#INTENT_VEH_OpenWindow##
ref#Vehicle_01004.pcm#zlb#male#打开全部车窗#INTENT_VEH_OpenAllWindow##
ref#Vehicle_01005.pcm#zlb#male#把全部车窗打开#INTENT_VEH_OpenAllWindow##
ref#Vehicle_01006.pcm#zlb#male#开启全部车窗#INTENT_VEH_OpenAllWindow##
ref#Vehicle_01007.pcm#zlb#male#打开左前车窗#INTENT_VEH_OpenWindowFrontLeftSeats##
ref#Vehicle_01008.pcm#zlb#male#把左前车窗打开#INTENT_VEH_OpenWindowFrontLeftSeats##
ref#Vehicle_01009.pcm#zlb#male#开启左前车窗#INTENT_VEH_OpenWindowFrontLeftSeats##
ref#Vehicle_01010.pcm#zlb#male#把主驾位车窗打开#INTENT_VEH_OpenWindowDriverSeat##
ref#Vehicle_01011.pcm#zlb#male#打开副驾驶车窗#INTENT_VEH_OpenWindowPassengerSeat##
ref#Vehicle_01012.pcm#zlb#male#打开左后车窗#INTENT_VEH_OpenWindowNearBackLeftseats##
ref#Vehicle_01013.pcm#zlb#male#把左后车窗打开#INTENT_VEH_OpenWindowNearBackLeftseats##
ref#Vehicle_01014.pcm#zlb#male#开启左后车窗#INTENT_VEH_OpenWindowNearBackLeftseats##
ref#Vehicle_01015.pcm#zlb#male#打开右后车窗#INTENT_VEH_OpenWindowNearBackRightseats##
ref#Vehicle_01016.pcm#zlb#male#把右后车窗打开#INTENT_VEH_OpenWindowNearBackRightseats##
ref#Vehicle_01017.pcm#zlb#male#开启右后车窗#INTENT_VEH_OpenWindowNearBackRightseats##
ref#Vehicle_01018.pcm#zlb#male#打开副驾车窗#INTENT_VEH_OpenWindowPassengerSeat##
ref#Vehicle_01019.pcm#zlb#male#打开右前车窗#INTENT_VEH_OpenWindowFrontRightSeats##
ref#Vehicle_01020.pcm#zlb#male#把副驾车窗打开#INTENT_VEH_OpenWindowPassengerSeat##
ref#Vehicle_01021.pcm#zlb#male#开启右前车窗#INTENT_VEH_OpenWindowFrontRightSeats##
ref#Vehicle_01022.pcm#zlb#male#打开前面车窗#INTENT_VEH_OpenWindowFrontSeats##
ref#Vehicle_01023.pcm#zlb#male#打开前排车窗#INTENT_VEH_OpenWindowFrontSeats##
ref#Vehicle_01024.pcm#zlb#male#把前面车窗打开#INTENT_VEH_OpenWindowFrontSeats##
ref#Vehicle_01025.pcm#zlb#male#把前边车窗打开#INTENT_VEH_OpenWindowFrontSeats##
ref#Vehicle_01026.pcm#zlb#male#打开后面车窗#INTENT_VEH_OpenWindowNearBackseats##
ref#Vehicle_01027.pcm#zlb#male#打开后排车窗#INTENT_VEH_OpenWindowNearBackseats##
ref#Vehicle_01028.pcm#zlb#male#把后面车窗打开#INTENT_VEH_OpenWindowNearBackseats##
ref#Vehicle_01029.pcm#zlb#male#把后边车窗打开#INTENT_VEH_OpenWindowNearBackseats##
ref#Vehicle_01030.pcm#zlb#male#开启后面车窗#INTENT_VEH_OpenWindowNearBackseats##
ref#Vehicle_01031.pcm#zlb#male#打开左边车窗#INTENT_VEH_OpenLeftWindow##
ref#Vehicle_01032.pcm#zlb#male#把左边车窗打开#INTENT_VEH_OpenLeftWindow##
ref#Vehicle_01033.pcm#zlb#male#开启左边车窗#INTENT_VEH_OpenLeftWindow##
ref#Vehicle_01034.pcm#zlb#male#打开右边车窗#INTENT_VEH_OpenRightWindow##
ref#Vehicle_01035.pcm#zlb#male#把右边车窗打开#INTENT_VEH_OpenRightWindow##
ref#Vehicle_01036.pcm#zlb#male#开启右边车窗#INTENT_VEH_OpenRightWindow##
ref#Vehicle_01037.pcm#zlb#male#车窗打开一半#INTENT_VEH_OpenWindowsGap##
ref#Vehicle_01038.pcm#zlb#male#把车窗打开一半#INTENT_VEH_OpenWindowsGap##
ref#Vehicle_01039.pcm#zlb#male#车窗半开#INTENT_VEH_OpenWindowsGap##
ref#Vehicle_01040.pcm#zlb#male#半开车窗#INTENT_VEH_OpenWindowsGap##
ref#Vehicle_01041.pcm#zlb#male#车窗开一点#INTENT_VEH_OpenWindowsGap##
ref#Vehicle_01042.pcm#zlb#male#关闭所有车窗#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01043.pcm#zlb#male#关上全部车窗#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01044.pcm#zlb#male#把全部车窗关上#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01045.pcm#zlb#male#关闭主驾驶车窗#INTENT_VEH_CloseWindowsNearDriverSeat##
ref#Vehicle_01046.pcm#zlb#male#主驾车窗关掉#INTENT_VEH_CloseWindowsNearDriverSeat##
ref#Vehicle_01047.pcm#zlb#male#帮我关上主驾驶车窗#INTENT_VEH_CloseWindowsNearDriverSeat##
ref#Vehicle_01048.pcm#zlb#male#关闭前排车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01049.pcm#zlb#male#关掉前排车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01050.pcm#zlb#male#我要关前边的车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01051.pcm#zlb#male#给我把前排车窗关上#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01052.pcm#zlb#male#帮我关前排车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01053.pcm#zlb#male#关闭后排车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01054.pcm#zlb#male#关后排车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01055.pcm#zlb#male#关一下后边的车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01056.pcm#zlb#male#帮我关了后排的车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01057.pcm#zlb#male#后边窗户关一下#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01058.pcm#zlb#male#把车窗关闭#INTENT_VEH_CloseWindow##
ref#Vehicle_01059.pcm#zlb#male#关掉车窗#INTENT_VEH_CloseWindow##
ref#Vehicle_01060.pcm#zlb#male#关闭车窗#INTENT_VEH_CloseWindow##
ref#Vehicle_01061.pcm#zlb#male#关闭全部车窗#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01062.pcm#zlb#male#把全部车窗关闭#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01063.pcm#zlb#male#关掉全部车窗#INTENT_VEH_CloseAllWindow##
ref#Vehicle_01064.pcm#zlb#male#关闭左前车窗#INTENT_VEH_CloseWindowsNearFontLeftSeats##
ref#Vehicle_01065.pcm#zlb#male#把左前车窗关闭#INTENT_VEH_CloseWindowsNearFontLeftSeats##
ref#Vehicle_01066.pcm#zlb#male#关掉左前车窗#INTENT_VEH_CloseWindowsNearFontLeftSeats##
ref#Vehicle_01067.pcm#zlb#male#把主驾位车窗关上#INTENT_VEH_CloseWindowsNearDriverSeat##
ref#Vehicle_01068.pcm#zlb#male#关闭副驾驶车窗#INTENT_VEH_CloseWindowsNearPassengerSeat##
ref#Vehicle_01069.pcm#zlb#male#关闭左后车窗#INTENT_VEH_CloseWindowsNearBackLeftseats##
ref#Vehicle_01070.pcm#zlb#male#把左后车窗关闭#INTENT_VEH_CloseWindowsNearBackLeftseats##
ref#Vehicle_01071.pcm#zlb#male#关掉左后车窗#INTENT_VEH_CloseWindowsNearBackLeftseats##
ref#Vehicle_01072.pcm#zlb#male#关闭右后车窗#INTENT_VEH_CloseWindowsNearBackRightseats##
ref#Vehicle_01073.pcm#zlb#male#把右后车窗关上#INTENT_VEH_CloseWindowsNearBackRightseats##
ref#Vehicle_01074.pcm#zlb#male#我想关右后车窗#INTENT_VEH_CloseWindowsNearBackRightseats##
ref#Vehicle_01075.pcm#zlb#male#帮我关闭副驾车窗#INTENT_VEH_CloseWindowsNearPassengerSeat##
ref#Vehicle_01076.pcm#zlb#male#关闭右前车窗#INTENT_VEH_CloseWindowsNearFontRightSeats##
ref#Vehicle_01077.pcm#zlb#male#把副驾车窗关了#INTENT_VEH_CloseWindowsNearPassengerSeat##
ref#Vehicle_01078.pcm#zlb#male#我要关掉右前车窗#INTENT_VEH_CloseWindowsNearFontRightSeats##
ref#Vehicle_01079.pcm#zlb#male#关闭前面车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01080.pcm#zlb#male#关上前排车窗#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01081.pcm#zlb#male#把前面车窗关掉#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01082.pcm#zlb#male#把前边车窗关闭#INTENT_VEH_CloseWindowsNearFontSeats##
ref#Vehicle_01083.pcm#zlb#male#关闭后面车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01084.pcm#zlb#male#关后排车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01085.pcm#zlb#male#把后面车窗关上#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01086.pcm#zlb#male#把后边车窗关闭#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01087.pcm#zlb#male#关掉后面车窗#INTENT_VEH_CloseWindowsNearBackseats##
ref#Vehicle_01088.pcm#zlb#male#关闭左边车窗#INTENT_VEH_CloseLeftWindow##
ref#Vehicle_01089.pcm#zlb#male#把左边车窗关闭#INTENT_VEH_CloseLeftWindow##
ref#Vehicle_01090.pcm#zlb#male#关掉左边车窗#INTENT_VEH_CloseLeftWindow##
ref#Vehicle_01091.pcm#zlb#male#关闭右边车窗#INTENT_VEH_CloseRightWindow##
ref#Vehicle_01092.pcm#zlb#male#把右边车窗关闭#INTENT_VEH_CloseRightWindow##
ref#Vehicle_01093.pcm#zlb#male#给我关掉右边车窗#INTENT_VEH_CloseRightWindow##
ref#Vehicle_01094.pcm#zlb#male#打开天窗#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01095.pcm#zlb#male#开启天窗#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01096.pcm#zlb#male#把天窗打开#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01097.pcm#zlb#male#把天窗开启#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01098.pcm#zlb#male#把天窗开开#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01099.pcm#zlb#male#开天窗#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01100.pcm#zlb#male#天窗开启#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01101.pcm#zlb#male#天窗开一半#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01102.pcm#zlb#male#天窗打开一半#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01103.pcm#zlb#male#把天窗打开一半#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01104.pcm#zlb#male#天窗半开#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01105.pcm#zlb#male#半开天窗#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01106.pcm#zlb#male#天窗翘起#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01107.pcm#zlb#male#天窗起翘#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01108.pcm#zlb#male#天窗翘起来#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01109.pcm#zlb#male#透透气#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01110.pcm#zlb#male#天窗透气#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01111.pcm#zlb#male#天窗通风#INTENT_VEH_TiltSunroof ##
ref#Vehicle_01112.pcm#zlb#male#天窗开一条缝#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01113.pcm#zlb#male#天窗开一点#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01114.pcm#zlb#male#开点天窗#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01115.pcm#zlb#male#天窗开一点点#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01116.pcm#zlb#male#天窗开一部分#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01117.pcm#zlb#male#开一些天窗#INTENT_VEH_OpenSunroofGap##
ref#Vehicle_01118.pcm#zlb#male#天窗开大一点#INTENT_VEH_ExpandSunroof##
ref#Vehicle_01119.pcm#zlb#male#天窗开大一些#INTENT_VEH_ExpandSunroof##
ref#Vehicle_01120.pcm#zlb#male#天窗再开大一点#INTENT_VEH_ExpandSunroof##
ref#Vehicle_01121.pcm#zlb#male#开大一点天窗#INTENT_VEH_ExpandSunroof##
ref#Vehicle_01122.pcm#zlb#male#天窗开小一点#INTENT_VEH_ShrinkSunroof##
ref#Vehicle_01123.pcm#zlb#male#天窗开小一些#INTENT_VEH_ShrinkSunroof##
ref#Vehicle_01124.pcm#zlb#male#开小一点天窗#INTENT_VEH_ShrinkSunroof##
ref#Vehicle_01125.pcm#zlb#male#关闭天窗#INTENT_VEH_CloseSunroof##
ref#Vehicle_01126.pcm#zlb#male#关上天窗#INTENT_VEH_CloseSunroof##
ref#Vehicle_01127.pcm#zlb#male#把天窗关闭#INTENT_VEH_CloseSunroof##
ref#Vehicle_01128.pcm#zlb#male#把天窗关上#INTENT_VEH_CloseSunroof##
ref#Vehicle_01129.pcm#zlb#male#关天窗#INTENT_VEH_CloseSunroof##
ref#Vehicle_01130.pcm#zlb#male#打开天窗窗帘#INTENT_VEH_OpenSunroof##
ref#Vehicle_01131.pcm#zlb#male#把天窗窗帘打开#INTENT_VEH_OpenSunroof##
ref#Vehicle_01132.pcm#zlb#male#天窗全开#INTENT_VEH_OpenWholeSunroof##
ref#Vehicle_01133.pcm#zlb#male#开启天窗窗帘#INTENT_VEH_OpenSunroof##
ref#Vehicle_01134.pcm#zlb#male#把天窗窗帘开开#INTENT_VEH_OpenSunroof##
ref#Vehicle_01135.pcm#zlb#male#打开遮阳帘#INTENT_VEH_OpenSunroof##
ref#Vehicle_01136.pcm#zlb#male#把卷阳帘打开#INTENT_VEH_OpenSunroof##
ref#Vehicle_01137.pcm#zlb#male#关闭天窗窗帘#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01138.pcm#zlb#male#把天窗窗帘关闭#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01139.pcm#zlb#male#关上天窗窗帘#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01140.pcm#zlb#male#把天窗窗帘关上#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01141.pcm#zlb#male#关天窗窗帘#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01142.pcm#zlb#male#关闭天窗窗帘#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01143.pcm#zlb#male#把遮阳帘关闭#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01144.pcm#zlb#male#卷阳帘关上#INTENT_VEH_CloseWholeSunroof##
ref#Vehicle_01145.pcm#zlb#male#我要看星星#INTENT_VEH_OpenSunroof##
ref#Vehicle_01146.pcm#zlb#male#我想看月亮#INTENT_VEH_OpenSunroof##
ref#Vehicle_01147.pcm#zlb#male#我要看看天#INTENT_VEH_OpenSunroof##
ref#Vehicle_01148.pcm#zlb#male#我要看蓝天白云#INTENT_VEH_OpenSunroof##
ref#Vehicle_01149.pcm#zlb#male#停止打开车窗#INTENT_VEH_OpenWindow##
ref#Vehicle_01150.pcm#zlb#male#停止#INTENT_VEH_OpenWindow##
ref#Vehicle_01151.pcm#zlb#male#停下来#INTENT_VEH_OpenWindow##
ref#Vehicle_01152.pcm#zlb#male#不要再开了#INTENT_VEH_OpenWindow##
ref#Vehicle_01153.pcm#zlb#male#挡风玻璃脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01154.pcm#zlb#male#挡风玻璃太脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01155.pcm#zlb#male#把挡风玻璃洗一下#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01156.pcm#zlb#male#把挡风玻璃洗洗#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01157.pcm#zlb#male#洗一下挡风玻璃#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01158.pcm#zlb#male#玻璃太脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01159.pcm#zlb#male#玻璃脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01160.pcm#zlb#male#车窗玻璃太脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01161.pcm#zlb#male#车窗玻璃脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01162.pcm#zlb#male#洗一下车窗玻璃#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01163.pcm#zlb#male#把车窗玻璃洗一下#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01164.pcm#zlb#male#把车窗玻璃洗洗#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01165.pcm#zlb#male#打开油箱盖#INTENT_VEH_OpenGascap##
ref#Vehicle_01166.pcm#zlb#male#油箱盖开一下#INTENT_VEH_OpenGascap##
ref#Vehicle_01167.pcm#zlb#male#开启油箱盖#INTENT_VEH_OpenGascap##
ref#Vehicle_01168.pcm#zlb#male#把油箱盖打开#INTENT_VEH_OpenGascap##
ref#Vehicle_01169.pcm#zlb#male#我想开启油箱盖#INTENT_VEH_OpenGascap##
ref#Vehicle_01170.pcm#zlb#male#关闭油箱盖#INTENT_VEH_CloseGascap##
ref#Vehicle_01171.pcm#zlb#male#把油箱盖关上#INTENT_VEH_CloseGascap##
ref#Vehicle_01172.pcm#zlb#male#关掉油箱盖#INTENT_VEH_CloseGascap##
ref#Vehicle_01173.pcm#zlb#male#油箱盖关一下#INTENT_VEH_CloseGascap##
ref#Vehicle_01174.pcm#zlb#male#我要关上油箱盖#INTENT_VEH_CloseGascap##
ref#Vehicle_01175.pcm#zlb#male#打开后备箱#INTENT_VEH_OpenTrunk##
ref#Vehicle_01176.pcm#zlb#male#后备箱开一下#INTENT_VEH_OpenTrunk##
ref#Vehicle_01177.pcm#zlb#male#开启后备箱#INTENT_VEH_OpenTrunk##
ref#Vehicle_01178.pcm#zlb#male#把后备箱打开#INTENT_VEH_OpenTrunk##
ref#Vehicle_01179.pcm#zlb#male#我想开启后备箱#INTENT_VEH_OpenTrunk##
ref#Vehicle_01180.pcm#zlb#male#关闭后备箱#INTENT_VEH_CloseTrunk##
ref#Vehicle_01181.pcm#zlb#male#把后备箱关上#INTENT_VEH_CloseTrunk##
ref#Vehicle_01182.pcm#zlb#male#关掉后备箱#INTENT_VEH_CloseTrunk##
ref#Vehicle_01183.pcm#zlb#male#后备箱关一下#INTENT_VEH_CloseTrunk##
ref#Vehicle_01184.pcm#zlb#male#我要关上后备箱#INTENT_VEH_CloseTrunk##
ref#Vehicle_01185.pcm#zlb#male#打开近光灯#INTENT_VEH_TurnOnLowBeam##
ref#Vehicle_01186.pcm#zlb#male#开启近光灯#INTENT_VEH_TurnOnLowBeam##
ref#Vehicle_01187.pcm#zlb#male#把近光灯打开#INTENT_VEH_TurnOnLowBeam##
ref#Vehicle_01188.pcm#zlb#male#我想开启近光灯#INTENT_VEH_TurnOnLowBeam##
ref#Vehicle_01189.pcm#zlb#male#关闭近光灯#INTENT_VEH_TurnOffLowBeam##
ref#Vehicle_01190.pcm#zlb#male#把近光灯关上#INTENT_VEH_TurnOffLowBeam##
ref#Vehicle_01191.pcm#zlb#male#关掉近光灯#INTENT_VEH_TurnOffLowBeam##
ref#Vehicle_01192.pcm#zlb#male#近光灯关一下#INTENT_VEH_TurnOffLowBeam##
ref#Vehicle_01193.pcm#zlb#male#我要关上近光灯#INTENT_VEH_TurnOffLowBeam##
ref#Vehicle_01194.pcm#zlb#male#打开远光灯#INTENT_VEH_TurnOnHighBeam ##
ref#Vehicle_01195.pcm#zlb#male#开启远光灯#INTENT_VEH_TurnOnHighBeam ##
ref#Vehicle_01196.pcm#zlb#male#把远光灯打开#INTENT_VEH_TurnOnHighBeam ##
ref#Vehicle_01197.pcm#zlb#male#我想开启远光灯#INTENT_VEH_TurnOnHighBeam ##
ref#Vehicle_01198.pcm#zlb#male#关闭远光灯#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01199.pcm#zlb#male#把远光灯关上#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01200.pcm#zlb#male#关掉远光灯#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01201.pcm#zlb#male#远光灯关一下#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01202.pcm#zlb#male#我要关上远光灯#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01203.pcm#zlb#male#关闭远光灯#INTENT_VEH_TurnOffHighBeam##
ref#Vehicle_01204.pcm#zlb#male#打开双跳灯#INTENT_VEH_TurnOnEmergencyFlashers##
ref#Vehicle_01205.pcm#zlb#male#开启双闪#INTENT_VEH_TurnOnEmergencyFlashers##
ref#Vehicle_01206.pcm#zlb#male#把双闪灯打开#INTENT_VEH_TurnOnEmergencyFlashers##
ref#Vehicle_01207.pcm#zlb#male#我想开启双跳灯#INTENT_VEH_TurnOnEmergencyFlashers##
ref#Vehicle_01208.pcm#zlb#male#把双跳灯关上#INTENT_VEH_TurnOffEmergencyFlashers##
ref#Vehicle_01209.pcm#zlb#male#关掉双闪#INTENT_VEH_TurnOffEmergencyFlashers##
ref#Vehicle_01210.pcm#zlb#male#双闪灯关一下#INTENT_VEH_TurnOffEmergencyFlashers##
ref#Vehicle_01211.pcm#zlb#male#我要关上双跳灯#INTENT_VEH_TurnOffEmergencyFlashers##
ref#Vehicle_01212.pcm#zlb#male#关闭双跳灯#INTENT_VEH_TurnOffEmergencyFlashers##
ref#Vehicle_01213.pcm#zlb#male#打开雾灯#INTENT_VEH_TurnOnFogLamps##
ref#Vehicle_01214.pcm#zlb#male#开启雾灯#INTENT_VEH_TurnOnFogLamps##
ref#Vehicle_01215.pcm#zlb#male#把雾灯打开#INTENT_VEH_TurnOnFogLamps##
ref#Vehicle_01216.pcm#zlb#male#我想开启雾灯#INTENT_VEH_TurnOnFogLamps##
ref#Vehicle_01217.pcm#zlb#male#把雾灯关上#INTENT_VEH_TurnOffFogLamps##
ref#Vehicle_01218.pcm#zlb#male#关掉雾灯#INTENT_VEH_TurnOffFogLamps##
ref#Vehicle_01219.pcm#zlb#male#雾灯关一下#INTENT_VEH_TurnOffFogLamps##
ref#Vehicle_01220.pcm#zlb#male#我要关上雾灯#INTENT_VEH_TurnOffFogLamps##
ref#Vehicle_01221.pcm#zlb#male#关闭雾灯#INTENT_VEH_TurnOffFogLamps##
ref#Vehicle_01222.pcm#zlb#male#打开车内氛围灯#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01223.pcm#zlb#male#开启车内氛围灯#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01224.pcm#zlb#male#把车内氛围灯打开#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01225.pcm#zlb#male#我想开启车内氛围灯#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01226.pcm#zlb#male#关闭车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01227.pcm#zlb#male#把车内氛围灯关上#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01228.pcm#zlb#male#关掉车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01229.pcm#zlb#male#车内氛围灯关一下#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01230.pcm#zlb#male#我要关上车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01231.pcm#zlb#male#关闭车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01232.pcm#zlb#male#打开主驾驶车窗#INTENT_VEH_OpenWindowDriverSeat##
ref#Vehicle_01233.pcm#zlb#male#开启车内氛围灯#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01234.pcm#zlb#male#把车内氛围灯打开#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01235.pcm#zlb#male#我想开启车内氛围灯#INTENT_VEH_TurnOnAtmosphereLamp##
ref#Vehicle_01236.pcm#zlb#male#关闭车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01237.pcm#zlb#male#把车内氛围灯关上#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01238.pcm#zlb#male#关掉车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01239.pcm#zlb#male#车内氛围灯关一下#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01240.pcm#zlb#male#我要关上车内氛围灯#INTENT_VEH_TurnOffAtmosphereLamp##
ref#Vehicle_01241.pcm#zlb#male#打开雨刮器#INTENT_VEH_TurnOnWiper##
ref#Vehicle_01242.pcm#zlb#male#雨刷器开了#INTENT_VEH_TurnOnWiper##
ref#Vehicle_01243.pcm#zlb#male#开一下雨刮器#INTENT_VEH_TurnOnWiper##
ref#Vehicle_01244.pcm#zlb#male#启动雨刷器#ref#Vehicle_01245.pcm#zlb#male#开启雨刷器#INTENT_VEH_TurnOnWiper##
ref#Vehicle_01246.pcm#zlb#male#关闭雨刮器#INTENT_VEH_TurnOffWiper##
ref#Vehicle_01247.pcm#zlb#male#给我把雨刷器关上#INTENT_VEH_TurnOffWiper##
ref#Vehicle_01248.pcm#zlb#male#关掉雨刷片#INTENT_VEH_TurnOffWiper##
ref#Vehicle_01249.pcm#zlb#male#我要关雨刷器#INTENT_VEH_TurnOffWiper##
ref#Vehicle_01250.pcm#zlb#male#帮我关了雨刷片#INTENT_VEH_TurnOffWiper##
ref#Vehicle_01251.pcm#zlb#male#清洁前挡#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01252.pcm#zlb#male#前档玻璃脏了#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01253.pcm#zlb#male#清洗前档玻璃#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01254.pcm#zlb#male#挡风玻璃清洗一下#INTENT_VEH_TurnOnWiperCleaning##
ref#Vehicle_01255.pcm#zlb#male#前挡风太脏了#INTENT_VEH_TurnOnWiperCleaning##
