#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#slotname;#slotvalue;
head
ref#Med0104025.pcm#wangjunyi#male#打开音乐#INTENT_Ent_Media_PlayMusic##
ref#Med0104027.pcm#wangjunyi#male#我要播放音乐#INTENT_Ent_Media_PlayMusic##
ref#Med0104034.pcm#wangjunyi#male#我要听歌#INTENT_Ent_Media_PlayMusic##
ref#Med0201041.pcm#gaoyao#female#播放音乐#INTENT_Ent_Media_PlayMusic##
ref#Med0201045.pcm#gaoyao#female#放个歌#INTENT_Ent_Media_PlayMusic##
ref#Med0201046.pcm#gaoyao#female#我要听个小曲#INTENT_Ent_Media_PlayMusic##
ref#Med0201049.pcm#gaoyao#female#播放点歌曲#INTENT_Ent_Media_PlayMusic##
ref#Med0201051.pcm#gaoyao#female#随便来首歌#INTENT_Ent_Media_PlayMusic##
ref#Med0201053.pcm#gaoyao#female#开始放歌#INTENT_Ent_Media_PlayMusic##
ref#Med0201054.pcm#gaoyao#female#给我随便来首歌#INTENT_Ent_Media_PlayMusic##
ref#0002_lifei_male.pcm#Lifei#male#来一首歌曲#INTENT_Ent_Media_PlayMusic##
ref#0004_lifei_male.pcm#Lifei#male#我想听歌#INTENT_Ent_Media_PlayMusic##
ref#0008_lifei_male.pcm#Lifei#male#来首歌#INTENT_Ent_Media_PlayMusic##
ref#0009_songxia_female.pcm#Songxia#female#音乐走起#INTENT_Ent_Media_PlayMusic##
ref#Med02014050.pcm#zhanglei#female#暂停一下#INTENT_Ent_Media_PauseMusic##
ref#Med02014051.pcm#zhanglei#female#暂停播放#INTENT_Ent_Media_PauseMusic##
ref#Med02014053.pcm#zhanglei#female#音乐暂停#INTENT_Ent_Media_PauseMusic##
ref#0012_lifei_male.pcm#Lifei#male#暂停音乐#INTENT_Ent_Media_PauseMusic##
ref#0013_songxia_female_001.pcm#Songxia#female#停止播放音乐#INTENT_Ent_Media_PauseMusic##
ref#0013_songxia_female_002.pcm#Songxia#female#停止音乐#INTENT_Ent_Media_StopMusic##
ref#0014_lifei_male.pcm#Lifei#male#音乐暂停#INTENT_Ent_Media_PauseMusic##
ref#0015_songxia_female.pcm#Songxia#female#暂停播放#INTENT_Ent_Media_PauseMusic##
ref#0016_lifei_male.pcm#Lifei#male#停止播放#INTENT_Ent_Media_PauseMusic##
ref#Med0201001.pcm#gaoyao#female#继续播放#INTENT_Ent_Media_ResumeMusic##
ref#Med0201002.pcm#gaoyao#female#能不能帮我恢复播放#INTENT_Ent_Media_ResumeMusic##
ref#Med0201003.pcm#gaoyao#female#请继续播放#INTENT_Ent_Media_ResumeMusic##
ref#Med02014055.pcm#zhanglei#female#继续播放#INTENT_Ent_Media_ResumeMusic##
ref#Med02014056.pcm#zhanglei#female#恢复播放#INTENT_Ent_Media_ResumeMusic##
ref#Med02014057.pcm#zhanglei#female#继续播放音乐#INTENT_Ent_Media_ResumeMusic##
ref#Med02014058.pcm#zhanglei#female#继续播放歌曲#INTENT_Ent_Media_ResumeMusic##
ref#Med02014059.pcm#zhanglei#female#恢复播放歌曲#INTENT_Ent_Media_ResumeMusic##
ref#Med02014060.pcm#zhanglei#female#恢复播放音乐#INTENT_Ent_Media_ResumeMusic##
ref#0018_lifei_male.pcm#Lifei#male#继续播放音乐#INTENT_Ent_Media_ResumeMusic##
ref#0019_wangxu_male.pcm#Songxia#female#继续收听歌曲#INTENT_Ent_Media_ResumeMusic##
ref#0020_lifei_male.pcm#Lifei#male#音乐继续播放#INTENT_Ent_Media_ResumeMusic##
ref#0021_songxia_female.pcm#Songxia#female#音乐继续#INTENT_Ent_Media_ResumeMusic##
ref#0022_lifei_male.pcm#Lifei#male#继续播放#INTENT_Ent_Media_ResumeMusic##
ref#0023_songxia_female.pcm#Songxia#female#播放#INTENT_Ent_Media_ResumeMusic##
ref#0024_lifei_male.pcm#Lifei#male#音乐继续#INTENT_Ent_Media_ResumeMusic##
ref#Med0108035.pcm#yangli#female#听蓝牙音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Bluetooth
ref#Med0108036.pcm#yangli#female#播放首蓝牙音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Bluetooth
ref#Med0108037.pcm#yangli#female#我要放蓝牙歌曲#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Bluetooth
ref#Med0108038.pcm#yangli#female#我想听个蓝牙音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Bluetooth
ref#Med0108039.pcm#yangli#female#来首蓝牙歌曲#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Bluetooth
ref#Med0108044.pcm#yangli#female#听U盘音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_USB
ref#Med0108049.pcm#yangli#female#放个U盘的歌曲#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_USB
ref#Med02014002.pcm#zhanglei#female#切音频源到USB#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_USB
ref#Med02014005.pcm#zhanglei#female#我想切换音源到USB#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_USB
ref#0032_lifei_male.pcm#Lifei#male#播放USB歌曲#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_USB
ref#online_01013.pcm#zhanglei#female#打开在线音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Online
ref#online_01014.pcm#zhanglei#female#我要听在线音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Online
ref#online_01016.pcm#zhanglei#female#听在线音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Online
ref#online_01023.pcm#zhanglei#female#来首网络歌曲#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Online
ref#online_01024.pcm#zhanglei#female#切换到网络音乐#INTENT_Ent_Media_PlayMusicBySource#RECOG_SLOT_Ent_Source#SpeechEntertainmentSource_Online
ref#Med0106049.pcm#chenbinglin#female#放个多远都要在一起#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#多远都要在一起
ref#Med0107004.pcm#fangshu#female#我要播首大王叫我来巡山#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#大王叫我来巡山
ref#Med0107007.pcm#fangshu#female#我想放首小眼睛#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#小眼睛
ref#Med0107014.pcm#fangshu#female#我想听Hello#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#Hello
ref#Med0107025.pcm#fangshu#female#我要切换到愿得一人心#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#愿得一人心
ref#Med0201057.pcm#gaoyao#female#我要听何日再相见神雕侠侣主题曲#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#何日再相见神雕侠侣主题曲
ref#Med0201058.pcm#gaoyao#female#放泡沫#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#泡沫
ref#0039_songxia_female.pcm#Songxia#female#来一首月光#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#月光
ref#0041_songxia_female.pcm#Songxia#female#播放歌曲风继续吹#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#风继续吹
ref#0042_lifei_male.pcm#Lifei#male#我要听在那遥远的地方#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#在那遥远的地方
ref#0043_songxia_female.pcm#Songxia#female#广岛之恋#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#广岛之恋
ref#0045_songxia_female.pcm#Songxia#female#听何日君再来#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#何日君再来
ref#0048_lifei_male.pcm#Lifei#male#歌曲心中的日月#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#心中的日月
ref#0049_songxia_female.pcm#Songxia#female#播放八度空间专辑#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_AlbumName#八度空间
ref#0050_lifei_male.pcm#Lifei#male#播放专辑Jay#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_AlbumName#Jay
ref#Med0105045.pcm#xuyiao#male#播放TFBOYS的音乐#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName#Tfboys
ref#0069_songxia_female.pcm#Songxia#female#播放所有五月天的歌#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName#五月天
ref#Med_add01001.pcm#zhanglei#female#播放蓝调音乐#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_GenreName#蓝调
ref#Med_add01002.pcm#zhanglei#female#听首经典摇滚歌曲#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_GenreName#经典摇滚
ref#Med_add01003.pcm#zhanglei#female#我要听乡村音乐#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_GenreName#乡村
ref#Med0107031.pcm#fangshu#female#播放蔡依林的我知道你很难过#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#蔡依林;我知道你很难过
ref#Med0107036.pcm#fangshu#female#听首海鸣威的你的承诺#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#海鸣威;你的承诺
ref#Med0107049.pcm#fangshu#female#我要听李健的Feeling Good#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#李健;Feelinggood
ref#Med0201008.pcm#gaoyao#female#我要听Beyond的光辉岁月#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#Beyond;光辉岁月
ref#Med0201015.pcm#gaoyao#female#请播放Michael Jackson的Dangerous#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#Michael Jackson;Dangerous
ref#Med0201028.pcm#gaoyao#female#现在放沙金氏史蒂文斯的因为爱你#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#沙金氏史蒂文斯;因为爱你
ref#0082_lifei_male.pcm#Lifei#male#窦唯无地自容#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#窦唯;无地自容
ref#Med_add01029.pcm#zhanglei#female#这是什么歌#INTENT_Ent_Media_QueryMusic##
ref#Med_add01030.pcm#zhanglei#female#这首歌叫什么#INTENT_Ent_Media_QueryMusic##
ref#Med_add01031.pcm#zhanglei#female#歌名是什么#INTENT_Ent_Media_QueryMusic##
ref#Med_add01032.pcm#zhanglei#female#这首歌的歌名#INTENT_Ent_Media_QueryMusic##
ref#Med_add01033.pcm#zhanglei#female#这首歌叫什么名字#INTENT_Ent_Media_QueryMusic##
ref#Med_add01034.pcm#zhanglei#female#这是谁的歌#INTENT_Ent_Media_QueryArtist##
ref#Med_add01035.pcm#zhanglei#female#这首歌是谁唱的#INTENT_Ent_Media_QueryArtist##
ref#Med_add01036.pcm#zhanglei#female#这歌的演唱者是谁#INTENT_Ent_Media_QueryArtist##
ref#Med_add01037.pcm#zhanglei#female#谁唱的这首歌#INTENT_Ent_Media_QueryArtist##
ref#Med_add01038.pcm#zhanglei#female#我想知道这歌是谁唱的#INTENT_Ent_Media_QueryArtist##
ref#Med_add01039.pcm#zhanglei#female#哪个歌手唱的这首歌#INTENT_Ent_Media_QueryArtist##
ref#Med0105020.pcm#xuyiao#male#上一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med0105022.pcm#xuyiao#male#我要播放上一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med0105023.pcm#xuyiao#male#我要前一首歌曲#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med0105025.pcm#xuyiao#male#我要播放上一个音乐#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med02014040.pcm#zhanglei#female#上一首歌曲#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med02014042.pcm#zhanglei#female#换到上一首歌曲#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#0110_lifei_male8000hz.pcm#Lifei#male#收听上一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#0117_songxia_female.pcm#Songxia#female#我要听上一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#0119_songxia_female.pcm#Songxia#female#播放上一首#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Previous
ref#Med0105029.pcm#xuyiao#male#我要播放后一首音乐#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#Med02014047.pcm#zhanglei#female#切到下一首#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#0122_lifei_male.pcm#Lifei#male#收听下一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#0123_songxia_female8000hz.pcm#Songxia#female#下一曲#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#0128_lifei_male.pcm#Lifei#male#我要听下一首歌#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#0132_lifei_male.pcm#Lifei#male#退出音乐#INTENT_Ent_Media_StopMusic##
ref#0133_songxia_female.pcm#Songxia#female#关闭音乐#INTENT_Ent_Media_StopMusic##
ref#0134_lifei_male.pcm#Lifei#male#结束音乐#INTENT_Ent_Media_StopMusic##
ref#0135_songxia_female.pcm#Songxia#female#我不想听歌了#INTENT_Ent_Media_StopMusic##
ref#0136_lifei_male.pcm#Lifei#male#我不要听歌了#INTENT_Ent_Media_StopMusic##
ref#0137_songxia_female.pcm#Songxia#female#我不想听歌曲了#INTENT_Ent_Media_StopMusic##
ref#0138_lifei_male.pcm#Lifei#male#音乐别播了#INTENT_Ent_Media_StopMusic##
ref#0084_lifei_male.pcm#Lifei#male#任意播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#0085_songxia_female.pcm#Songxia#female#随意播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#0086_lifei_male8000hz.pcm#Lifei#male#设置为随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#0087_songxia_female.pcm#Songxia#female#设为随机#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#Med0108030.pcm#yangli#female#设置为随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#Med0108029.pcm#yangli#female#设为单曲循环#INTENT_Ent_Media_SingleRepeat##
ref#Med0108032.pcm#yangli#female#设成单曲循环模式#INTENT_Ent_Media_SingleRepeat##
ref#Med02014075.pcm#zhanglei#female#单曲重复播放模式#INTENT_Ent_Media_SingleRepeat##
ref#Med02014076.pcm#zhanglei#female#帮我调为单曲重复播放模式#INTENT_Ent_Media_SingleRepeat##
ref#Med02014077.pcm#zhanglei#female#我想调为单曲重复播放模式#INTENT_Ent_Media_SingleRepeat##
ref#Med02014078.pcm#zhanglei#female#调为单曲重复播放模式#INTENT_Ent_Media_SingleRepeat##
ref#0095_songxia_female.pcm#Songxia#female#单曲循环#INTENT_Ent_Media_SingleRepeat##
ref#0096_lifei_male.pcm#Lifei#male#单曲重复播放#INTENT_Ent_Media_SingleRepeat##
ref#0097_songxia_female.pcm#Songxia#female#单曲循环播放#INTENT_Ent_Media_SingleRepeat##
ref#0098_lifei_male.pcm#Lifei#male#音乐设置成单曲循环#INTENT_Ent_Media_SingleRepeat##
ref#0099_songxia_female8000hz.pcm#Songxia#female#设置成单曲循环#INTENT_Ent_Media_SingleRepeat##
ref#0100_lifei_male.pcm#Lifei#male#循环播放这一首歌#INTENT_Ent_Media_SingleRepeat##
ref#0101_songxia_female.pcm#Songxia#female#单曲重复#INTENT_Ent_Media_SingleRepeat##
ref#Med0108033.pcm#yangli#female#我想切换为全部循环#INTENT_Ent_Media_AllRepeat##
ref#Med02014083.pcm#zhanglei#female#全部重复#INTENT_Ent_Media_AllRepeat##
ref#Med02014084.pcm#zhanglei#female#我想全部重复#INTENT_Ent_Media_AllRepeat##
ref#Med02014085.pcm#zhanglei#female#设置成全部重复#INTENT_Ent_Media_AllRepeat##
ref#Med02014086.pcm#zhanglei#female#帮我全部重复#INTENT_Ent_Media_AllRepeat##
ref#Med02014087.pcm#zhanglei#female#能不能调为全部重复#INTENT_Ent_Media_AllRepeat##
ref#0102_lifei_male.pcm#Lifei#male#全部循环#INTENT_Ent_Media_AllRepeat##
ref#0103_songxia_female.pcm#Songxia#female#全部重复#INTENT_Ent_Media_AllRepeat##
ref#0104_lifei_male.pcm#Lifei#male#全部循环播放#INTENT_Ent_Media_AllRepeat##
ref#0106_lifei_male8000hz.pcm#Lifei#male#设置成全部循环#INTENT_Ent_Media_AllRepeat##
ref#0107_songxia_female8000hz.pcm#Songxia#female#循环播放所有歌曲#INTENT_Ent_Media_AllRepeat##
ref#Med_add01040.pcm#zhanglei#female#顺序播放#INTENT_Ent_Media_PlayAll##
ref#Med_add01041.pcm#zhanglei#female#按顺序播放#INTENT_Ent_Media_PlayAll##
ref#Med_add01042.pcm#zhanglei#female#设置为顺序播放#INTENT_Ent_Media_PlayAll##
ref#Med_add01043.pcm#zhanglei#female#设置为顺序播放模式#INTENT_Ent_Media_PlayAll##
ref#Med_add01044.pcm#zhanglei#female#顺序播放模式#INTENT_Ent_Media_PlayAll##
ref#Med_add01045.pcm#zhanglei#female#帮我顺序播放#INTENT_Ent_Media_PlayAll##
ref#Med0105006.pcm#xuyiao#male#随便播首歌#INTENT_Ent_Media_PlayMusic##
ref#Med0105007.pcm#xuyiao#male#随便来个音乐#INTENT_Ent_Media_PlayMusic##
ref#Med0105008.pcm#xuyiao#male#随便来首歌听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105009.pcm#xuyiao#male#随便放点儿歌听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105010.pcm#xuyiao#male#我要随便播首歌#INTENT_Ent_Media_PlayMusic##
ref#Med0105011.pcm#xuyiao#male#我想随便来点儿音乐#INTENT_Ent_Media_PlayMusic##
ref#Med0105012.pcm#xuyiao#male#我想随便放点儿歌#INTENT_Ent_Media_PlayMusic##
ref#Med0105013.pcm#xuyiao#male#我要随便播首歌听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105014.pcm#xuyiao#male#我想随便放点儿音乐听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105015.pcm#xuyiao#male#随便听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105016.pcm#xuyiao#male#我要随便听#INTENT_Ent_Media_PlayMusic##
ref#Med0105017.pcm#xuyiao#male#切换到随便听听#INTENT_Ent_Media_PlayMusic##
ref#Med0105018.pcm#xuyiao#male#我想调到随便听#INTENT_Ent_Media_PlayMusic##
ref#Med0108031.pcm#yangli#female#切换成全部循环#INTENT_Ent_Media_AllRepeat##
ref#2c5aef4d13e52634_tts.wav#tts#female#来首唯一#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_TitleName#唯一
ref#3d92475bec28ff29_tts.wav#tts#female#收听张杰的默#INTENT_Ent_Media_PlayMusic#RECOG_SLOT_Ent_ArtistName;RECOG_SLOT_Ent_TitleName#张杰;默
ref#6f31e8836535f192_tts.wav#tts#female#我要听下一首#INTENT_Ent_Media_SkipTrack#RECOG_SLOT_Main_SkipDirection#SpeechSkipDirection_Next
ref#ff61b791c5fc8fa6_tts.wav#tts#female#音乐停一下#INTENT_Ent_Media_PauseMusic##
ref#bf45303e1829ea6d_tts.wav#tts#female#随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#ba72b6ea54f8aad9_tts.wav#tts#female#激活随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#365635b5fe5a7a6e_tts.wav#tts#female#激活随机功能#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#18e6e8d696c8c7ce_tts.wav#tts#female#全部随机播放模式#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#c9d22828931d41a9_tts.wav#tts#female#我想全部随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#2e4ca3c21629f59e_tts.wav#tts#female#帮我调为全部随机播放模式#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#fe229c41d05b8f48_tts.wav#tts#female#设置成全部随机播放模式#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#bb1d763abb55879c_tts.wav#tts#female#我要设置成随机播放#INTENT_Ent_Media_ShuffleCurrentSelection_On##
ref#93ab6ef3d8c81cec_tts.wav#tts#female#把循环设置成全部播放#INTENT_Ent_Media_AllRepeat##
