#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#;slot names#;slot values
head
ref#Wea01025001.pcm#chenchen#female#今天天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025002.pcm#chenchen#female#今天天气如何#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025003.pcm#chenchen#female#今天天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025004.pcm#chenchen#female#现在天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#
ref#Wea01025005.pcm#chenchen#female#打开天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#
ref#Wea01025006.pcm#chenchen#female#播报天气情况#INTENT_Apps_Weather_Inquiry##
ref#Wea01025007.pcm#chenchen#female#播报天气#INTENT_Apps_Weather_Inquiry##
ref#Wea01025008.pcm#chenchen#female#播放天气情况#INTENT_Apps_Weather_Inquiry##
ref#Wea01025009.pcm#chenchen#female#天气怎么样#INTENT_Apps_Weather_Inquiry##
ref#Wea01025010.pcm#chenchen#female#天气如何#INTENT_Apps_Weather_Inquiry##
ref#Wea01025011.pcm#chenchen#female#星期二天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=tuesday
ref#Wea01025012.pcm#chenchen#female#6月18号天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#dayNum=18 month=june
ref#Wea01025013.pcm#chenchen#female#周三的天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=wednesday
ref#Wea01025014.pcm#chenchen#female#打开星期四天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=thursday
ref#Wea01025015.pcm#chenchen#female#现在天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025016.pcm#chenchen#female#播放星期五天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=friday
ref#Wea01025017.pcm#chenchen#female#播报周一天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=monday
ref#Wea01025018.pcm#chenchen#female#今天几度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025019.pcm#chenchen#female#现在多少度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025020.pcm#chenchen#female#今天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#Wea01025021.pcm#chenchen#female#今天天气冷不冷#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;cold;冷不冷
ref#Wea01025022.pcm#chenchen#female#今天热不热#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;warm;热不热
ref#Wea01025023.pcm#chenchen#female#今天天气凉不凉#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;rain;凉不凉
ref#Wea01025024.pcm#chenchen#female#今冷不冷#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;cold;冷不冷
ref#Wea01025025.pcm#chenchen#female#今天下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;rain;雨
ref#Wea01025026.pcm#chenchen#female#今天下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;snow;雪
ref#Wea01025027.pcm#chenchen#female#今天有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;rain;雨
ref#Wea01025028.pcm#chenchen#female#今天有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;snow;雪
ref#Wea01025029.pcm#chenchen#female#下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#rain;雨
ref#Wea01025030.pcm#chenchen#female#下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#snow;雪
ref#Wea01025031.pcm#chenchen#female#有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#rain;雨
ref#Wea01025032.pcm#chenchen#female#有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#snow;雪
ref#Wea01026021.pcm#xianglei#male#上海明天天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026022.pcm#xianglei#male#明天上海的天气如何#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026023.pcm#xianglei#male#上海明天的天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026024.pcm#xianglei#male#打开上海明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026025.pcm#xianglei#male#播报明天上海的天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026026.pcm#xianglei#male#播放上海明天的天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026027.pcm#xianglei#male#天气怎么样上海明天#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026028.pcm#xianglei#male#天气如何明天上海#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026029.pcm#xianglei#male#天气情况上海明天#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026031.pcm#xianglei#male#播报天气怎么样明天上海#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026032.pcm#xianglei#male#播放天气情况明天上海#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026033.pcm#xianglei#male#上海明天几度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026034.pcm#xianglei#male#上海明天多少度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026035.pcm#xianglei#male#上海明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026036.pcm#xianglei#male#明天上海几度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026037.pcm#xianglei#male#明天上海多少度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026038.pcm#xianglei#male#明天上海的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#Wea01026039.pcm#xianglei#male#上海明天下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;rain;雨
ref#Wea01026040.pcm#xianglei#male#上海明天下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;snow;下雪
ref#Wea01026041.pcm#xianglei#male#上海明天有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;rain;雨
ref#Wea01026042.pcm#xianglei#male#上海明天有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;snow;雪
ref#Wea01026043.pcm#xianglei#male#明天上海下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;rain;雨
ref#Wea01026044.pcm#xianglei#male#明天上海下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;snow;下雪
ref#Wea01026045.pcm#xianglei#male#明天上海有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;rain;雨
ref#Wea01026046.pcm#xianglei#male#明天上海有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=1;snow;雪
ref#0001_yanjingjing_female.pcm#YanJingjing#female#查询青岛的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#青岛
ref#0002_zhaowei_male.pcm#ZhaoWei#male#查下石家庄的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#石家庄
ref#0003_yanjingjing_female.pcm#YanJingjing#female#查查保定的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#保定
ref#0004_zhaowei_male.pcm#ZhaoWei#male#搜索南昌的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#南昌
ref#0005_yanjingjing_female.pcm#YanJingjing#female#搜一搜苏州的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#苏州
ref#0006_zhaowei_male.pcm#ZhaoWei#male#看看西安的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#西安
ref#0007_yanjingjing_female.pcm#YanJingjing#female#看一下温州的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#温州
ref#0008_zhaowei_male.pcm#ZhaoWei#male#我想查看杭州湾的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#杭州湾
ref#0009_yanjingjing_female.pcm#YanJingjing#female#杭州的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#杭州
ref#0010_zhaowei_male.pcm#ZhaoWei#male#天津天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#天津
ref#0011_yanjingjing_female.pcm#YanJingjing#female#徐州天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#徐州
ref#0012_zhaowei_male.pcm#ZhaoWei#male#查询上海的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#上海
ref#0013_yanjingjing_female.pcm#YanJingjing#female#看看济南的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#济南
ref#0014_zhaowei_male.pcm#ZhaoWei#male#搜索长春的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#长春
ref#0015_yanjingjing_female.pcm#YanJingjing#female#沈阳的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#沈阳
ref#0016_zhaowei_male.pcm#ZhaoWei#male#查询宁波明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#宁波;d=1
ref#0017_yanjingjing_female.pcm#YanJingjing#female#搜索长春周四的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#长春;weekday=Thursday
ref#0018_zhaowei_male.pcm#ZhaoWei#male#看看哈尔滨昨天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#哈尔滨;d=-1
ref#0019_yanjingjing_female.pcm#YanJingjing#female#看看哈尔滨1月5号的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#哈尔滨;dayNum=5 month=january
ref#0020_zhaowei_male.pcm#ZhaoWei#male#查询威海明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#威海;d=1
ref#0021_yanjingjing_female.pcm#YanJingjing#female#查询烟台2月17号的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#烟台;dayNum=17 month=february
ref#0022_zhaowei_male.pcm#ZhaoWei#male#我想查看杭州明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#杭州;d=1
ref#0023_yanjingjing_female.pcm#YanJingjing#female#查询广州明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#广州;d=1;d=1
ref#0024_zhaowei_male.pcm#ZhaoWei#male#查看西安未来三天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#西安;duration_days=3
ref#0025_yanjingjing_female.pcm#YanJingjing#female#搜索苏州周四的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#苏州;weekday=thursday
ref#0026_zhaowei_male.pcm#ZhaoWei#male#看看南京昨天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#南京;d=-1
ref#0027_yanjingjing_female.pcm#YanJingjing#female#看看无锡6月7号的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#无锡;dayNum=7 month=june
ref#0028_zhaowei_male.pcm#ZhaoWei#male#查询上海明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;d=1
ref#0029_yanjingjing_female.pcm#YanJingjing#female#查询南宁1月3号的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#南宁;dayNum=3 month=january
ref#0030_zhaowei_male.pcm#ZhaoWei#male#我想查看厦门明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#厦门;d=1
ref#0031_yanjingjing_female.pcm#YanJingjing#female#济南明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#济南;d=1
ref#0032_zhaowei_male.pcm#ZhaoWei#male#后天武汉的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#武汉;d=2
ref#0033_yanjingjing_female.pcm#YanJingjing#female#汉口后天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#汉口;d=2
ref#0034_zhaowei_male.pcm#ZhaoWei#male#看看后天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=2
ref#0035_yanjingjing_female.pcm#YanJingjing#female#查询明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0036_zhaowei_male.pcm#ZhaoWei#male#明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0037_yanjingjing_female.pcm#YanJingjing#female#3月6号的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#dayNum=6 month=march
ref#0038_zhaowei_male.pcm#ZhaoWei#male#搜索今天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#0039_yanjingjing_female.pcm#YanJingjing#female#查查明天的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0040_zhaowei_male.pcm#ZhaoWei#male#明天的天气情况#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0041_yanjingjing_female.pcm#YanJingjing#female#明天的天气状况怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0042_zhaowei_male.pcm#ZhaoWei#male#看看明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0043_yanjingjing_female.pcm#YanJingjing#female#查看后天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=2
ref#0044_zhaowei_male.pcm#ZhaoWei#male#查询今天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=0
ref#0045_yanjingjing_female.pcm#YanJingjing#female#前天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=-2
ref#0046_zhaowei_male.pcm#ZhaoWei#male#2月1号的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#dayNum=1 month=february
ref#0047_yanjingjing_female.pcm#YanJingjing#female#搜索明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0048_zhaowei_male.pcm#ZhaoWei#male#搜一搜明天的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#d=1
ref#0049_yanjingjing_female.pcm#YanJingjing#female#苏州这个星期的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#苏州;w=0
ref#0050_zhaowei_male.pcm#ZhaoWei#male#搜索上海下个星期的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海;w=1
ref#0051_yanjingjing_female.pcm#YanJingjing#female#看看西宁下个星期一的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#西宁;weekday=monday w=1
ref#0052_zhaowei_male.pcm#ZhaoWei#male#千岛湖这个星期的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#千岛湖;w=0
ref#0053_yanjingjing_female.pcm#YanJingjing#female#我要看合肥上周一的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#合肥;weekday=monday w=-1
ref#0054_zhaowei_male.pcm#ZhaoWei#male#我要看海口下周五的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#海口;weekday=friday w=1
ref#0055_yanjingjing_female.pcm#YanJingjing#female#苏州这周的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#苏州;w=0
ref#0056_zhaowei_male.pcm#ZhaoWei#male#搜索郑州下周的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#郑州;w=1
ref#0057_yanjingjing_female.pcm#YanJingjing#female#看看芜湖下个星期三的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#芜湖;weekday=wednesday w=1
ref#0058_zhaowei_male.pcm#ZhaoWei#male#南宁这周的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#南宁;w=0
ref#0059_yanjingjing_female.pcm#YanJingjing#female#我要看银川上周二的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#银川;weekday=tuesday w=-1
ref#0060_zhaowei_male.pcm#ZhaoWei#male#我要看西宁下周一的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#西宁;weekday=monday w=1
ref#0061_yanjingjing_female.pcm#YanJingjing#female#西安这周五的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#西安;weekday=friday w=0
ref#0062_zhaowei_male.pcm#ZhaoWei#male#北京下周三的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#北京;weekday=wednesday w=1
ref#0063_yanjingjing_female.pcm#YanJingjing#female#沈阳上周四的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#沈阳;weekday=thursday w=-1;
ref#0064_zhaowei_male.pcm#ZhaoWei#male#这个星期的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#0065_yanjingjing_female.pcm#YanJingjing#female#搜索下个星期的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=1
ref#0066_zhaowei_male.pcm#ZhaoWei#male#看看下个星期五的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=friday w=1
ref#0067_yanjingjing_female.pcm#YanJingjing#female#这个星期三的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=wednesday w=0
ref#0068_zhaowei_male.pcm#ZhaoWei#male#我要看上周二的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=tuesday w=-1
ref#0069_yanjingjing_female.pcm#YanJingjing#female#我要看下周四的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=thursday w=1
ref#0070_zhaowei_male.pcm#ZhaoWei#male#这周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#0071_yanjingjing_female.pcm#YanJingjing#female#这周温度怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#0072_zhaowei_male.pcm#ZhaoWei#male#这周的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#0073_yanjingjing_female.pcm#YanJingjing#female#搜一搜下周的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=1
ref#0074_zhaowei_male.pcm#ZhaoWei#male#搜索下周的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=1
ref#0075_yanjingjing_female.pcm#YanJingjing#female#看看下周六的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=saturday w=1
ref#0076_zhaowei_male.pcm#ZhaoWei#male#这个星期五的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=friday w=0
ref#0077_yanjingjing_female.pcm#YanJingjing#female#我要看上个星期二的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=tuesday w=-1
ref#0078_zhaowei_male.pcm#ZhaoWei#male#我要看下个星期三的温度#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=wednesday w=1
ref#0079_yanjingjing_female.pcm#YanJingjing#female#天气怎么样#INTENT_Apps_Weather_Inquiry##
ref#0080_zhaowei_male.pcm#ZhaoWei#male#天气如何#INTENT_Apps_Weather_Inquiry##
ref#0081_yanjingjing_female.pcm#YanJingjing#female#天气好不好#INTENT_Apps_Weather_Inquiry##
ref#0082_zhaowei_male.pcm#ZhaoWei#male#天气热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#warm;热
ref#0083_yanjingjing_female.pcm#YanJingjing#female#天气冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#cold;冷
ref#0084_zhaowei_male.pcm#ZhaoWei#male#温度怎么样#INTENT_Apps_Weather_Inquiry##
ref#0085_yanjingjing_female.pcm#YanJingjing#female#温度高吗#INTENT_Apps_Weather_Inquiry##
ref#0086_zhaowei_male.pcm#ZhaoWei#male#温度低吗#INTENT_Apps_Weather_Inquiry##
ref#0087_yanjingjing_female.pcm#YanJingjing#female#温度如何#INTENT_Apps_Weather_Inquiry##
ref#0088_zhaowei_male.pcm#ZhaoWei#male#天气预报#INTENT_Apps_Weather_Inquiry##
ref#0089_yanjingjing_female.pcm#YanJingjing#female#今天北京下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=0;rain;雨
ref#0090_zhaowei_male.pcm#ZhaoWei#male#明天有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=1;rain;雨
ref#0091_yanjingjing_female.pcm#YanJingjing#female#今天南京下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#南京;d=0;snow;下雪
ref#0092_zhaowei_male.pcm#ZhaoWei#male#明天有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=1;snow;雪
ref#0093_yanjingjing_female.pcm#YanJingjing#female#今天上海冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=0;cold;冷
ref#0094_zhaowei_male.pcm#ZhaoWei#male#今天多云吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;cloudy;多云
ref#0095_yanjingjing_female.pcm#YanJingjing#female#今天晴天吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;sunny;晴天
ref#0096_zhaowei_male.pcm#ZhaoWei#male#今天有暴雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;rain;暴雨
ref#0097_yanjingjing_female.pcm#YanJingjing#female#热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#warm;热
ref#0098_zhaowei_male.pcm#ZhaoWei#male#热不热#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#warm;热
ref#0099_yanjingjing_female.pcm#YanJingjing#female#冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#cold;冷
ref#0100_zhaowei_male.pcm#ZhaoWei#male#冷不冷#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#cold;冷
ref#0101_yanjingjing_female.pcm#YanJingjing#female#北京今天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=0;rain;伞
ref#0102_zhaowei_male.pcm#ZhaoWei#male#需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#rain;伞
ref#0103_yanjingjing_female.pcm#YanJingjing#female#南京明天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#南京;d=1;rain;伞
ref#0104_zhaowei_male.pcm#ZhaoWei#male#北京后天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=2;rain;伞
ref#0105_yanjingjing_female.pcm#YanJingjing#female#这个星期北京下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;w=0;rain;雨
ref#0106_zhaowei_male.pcm#ZhaoWei#male#周四有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=thursday;rain;雨
ref#0107_yanjingjing_female.pcm#YanJingjing#female#下个星期哈尔滨下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#哈尔滨;w=1;snow;下雪
ref#0108_zhaowei_male.pcm#ZhaoWei#male#这个星期有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;snow;雪
ref#0109_yanjingjing_female.pcm#YanJingjing#female#这个星期沈阳冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName#沈阳;w=0
ref#0110_zhaowei_male.pcm#ZhaoWei#male#下周二冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=tuesday w=1;cold;冷;
ref#0111_yanjingjing_female.pcm#YanJingjing#female#周四广州热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#广州;weekday=thursday;warm;热
ref#0112_zhaowei_male.pcm#ZhaoWei#male#这周海南热不热#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#海南;w=0;warm;热
ref#0113_yanjingjing_female.pcm#YanJingjing#female#北京下周有暴雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;w=1;暴雨;rain
ref#0114_zhaowei_male.pcm#ZhaoWei#male#这个星期武汉热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#武汉;w=0;warm;热
ref#0115_yanjingjing_female.pcm#YanJingjing#female#厦门下个星期二要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#厦门;weekday=tuesday w=1;rain;伞
ref#0116_zhaowei_male.pcm#ZhaoWei#male#厦门这周要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#厦门;w=0;rain;伞
ref#0117_yanjingjing_female.pcm#YanJingjing#female#广州周三要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#广州;weekday=wednesday;rain;伞
ref#0118_zhaowei_male.pcm#ZhaoWei#male#周三需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=wednesday;rain;伞;
ref#0098_zhaowei_male.pcm#ZhaoWei#male#热不热#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#warm;热
ref#0099_yanjingjing_female.pcm#YanJingjing#female#冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#cold;冷
ref#0100_zhaowei_male.pcm#ZhaoWei#male#冷不冷#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#cold;冷
ref#0101_yanjingjing_female.pcm#YanJingjing#female#北京今天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=0;rain;伞;
ref#0102_zhaowei_male.pcm#ZhaoWei#male#需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#rain;伞
ref#0103_yanjingjing_female.pcm#YanJingjing#female#南京明天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#南京;d=1;rain;伞
ref#0104_zhaowei_male.pcm#ZhaoWei#male#北京后天要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=2;rain;伞
ref#0105_yanjingjing_female.pcm#YanJingjing#female#这个星期北京下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;w=0;rain;雨
ref#0106_zhaowei_male.pcm#ZhaoWei#male#周四有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=thursday;rain;雨
ref#0107_yanjingjing_female.pcm#YanJingjing#female#下个星期哈尔滨下雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#哈尔滨;w=1;snow;下雪
ref#0108_zhaowei_male.pcm#ZhaoWei#male#这个星期有雪吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;snow;雪
ref#0109_yanjingjing_female.pcm#YanJingjing#female#这个星期沈阳冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#沈阳;w=0;cold;冷
ref#0110_zhaowei_male.pcm#ZhaoWei#male#下周二冷吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=tuesday w=1;cold;冷
ref#0111_yanjingjing_female.pcm#YanJingjing#female#周四广州热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#广州;weekday=thursday;warm;热
ref#0112_zhaowei_male.pcm#ZhaoWei#male#这周海南热不热#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#海南;w=0;warm;热
ref#0113_yanjingjing_female.pcm#YanJingjing#female#北京下周有暴雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;w=1;rain;暴雨
ref#0114_zhaowei_male.pcm#ZhaoWei#male#这个星期武汉热吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#武汉;w=0;warm;热
ref#0115_yanjingjing_female.pcm#YanJingjing#female#厦门下个星期二要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#厦门;weekday=tuesday w=1;rain;伞
ref#0116_zhaowei_male.pcm#ZhaoWei#male#厦门这周要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#厦门;w=0;rain;伞
ref#0117_yanjingjing_female.pcm#YanJingjing#female#广州周三要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#广州;weekday=wednesday;rain;伞
ref#0118_zhaowei_male.pcm#ZhaoWei#male#周三需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=wednesday;rain;伞
ref#Weathwer_add01001.pcm#Zeff#male#查一下奉贤区的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#奉贤区
ref#Weathwer_add01002.pcm#Zeff#male#杭州天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#杭州
ref#Weathwer_add01003.pcm#Zeff#male#北京海淀区的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName#北京海淀区
ref#Weathwer_add01004.pcm#Zeff#male#朝阳区有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#朝阳区;rain;雨
ref#Weathwer_add01005.pcm#Zeff#male#上海有没有雾霾#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;air_quality;雾霾
ref#Weathwer_add01006.pcm#Zeff#male#西湖区刮风吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#西湖区;wind;风
ref#Weathwer_add01007.pcm#Zeff#male#去北京要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;rain;伞
ref#Weathwer_add01008.pcm#Zeff#male#去上海要不要拿伞#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;rain;伞
ref#Weathwer_add01009.pcm#Zeff#male#去杭州需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;rain;伞
ref#Weathwer_add01010.pcm#Zeff#male#去北京要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;sunny;墨镜
ref#Weathwer_add01011.pcm#Zeff#male#去黄浦区要不要拿墨镜#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#黄浦区;sunny;墨镜
ref#Weathwer_add01012.pcm#Zeff#male#到杭州下沙需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#黄浦区;sunny;墨镜
ref#Weathwer_add01013.pcm#Zeff#male#去朝阳区要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#朝阳区;air_quality;口罩
ref#Weathwer_add01014.pcm#Zeff#male#去上海要不要拿口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;air_quality;口罩
ref#Weathwer_add01015.pcm#Zeff#male#去余杭区需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#余杭区;air_quality;口罩
ref#Weathwer_add01016.pcm#Zeff#male#查一下上海浦东新区周三的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海浦东新区;weekday=wednesday
ref#Weathwer_add01017.pcm#Zeff#male#杭州上城区上周五天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#杭州上城区;weekday=friday w=-1
ref#Weathwer_add01018.pcm#Zeff#male#下城区5月20号天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#下城区;dayNum=20 month=may
ref#Weathwer_add01019.pcm#Zeff#male#杭州10月1号天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#杭州;dayNum=1 month=october
ref#Weathwer_add01020.pcm#Zeff#male#北京周二的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#北京;weekday=tuesday
ref#Weathwer_add01021.pcm#Zeff#male#北京东城区周二有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京东城区;weekday=tuesday;rain;雨
ref#Weathwer_add01022.pcm#Zeff#male#静安区后天有没有雾霾#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#静安区;d=2;air_quality;雾霾
ref#Weathwer_add01023.pcm#Zeff#male#杭州5月20号下不下雨#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=20 month=may;rain;雨
ref#Weathwer_add01024.pcm#Zeff#male#武汉10月1号下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#武汉;dayNum=1 month=october;rain;雨
ref#Weathwer_add01025.pcm#Zeff#male#杭州明天刮风吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;d=1;wind;风
ref#Weathwer_add01026.pcm#Zeff#male#周二去北京要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;weekday=tuesday;rain;伞
ref#Weathwer_add01027.pcm#Zeff#male#后天去上海要不要拿伞#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;d=2;rain;伞
ref#Weathwer_add01028.pcm#Zeff#male#5月20号去杭州需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=20 month=may;rain;伞
ref#Weathwer_add01029.pcm#Zeff#male#10月1号去杭州要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=1 month=october;rain;伞
ref#Weathwer_add01030.pcm#Zeff#male#明天去杭州需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;d=1;rain;伞
ref#Weathwer_add01031.pcm#Zeff#male#后天去北京要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#北京;d=2;sunny;墨镜
ref#Weathwer_add01032.pcm#Zeff#male#下周二去上海要不要拿墨镜#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#上海;weekday=tuesday w=1;sunny;墨镜
ref#Weathwer_add01033.pcm#Zeff#male#杭州5月20号需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=20 month=may;sunny;墨镜
ref#Weathwer_add01034.pcm#Zeff#male#杭州10月1号要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=1 month=october;sunny;墨镜
ref#Weathwer_add01035.pcm#Zeff#male#周五去杭州需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;weekday=friday;sunny;墨镜
ref#Weathwer_add01036.pcm#Zeff#male#周一去要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=monday;air_quality;口罩
ref#Weathwer_add01037.pcm#Zeff#male#后天去静安区要不要拿口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#静安区;d=2;air_quality;口罩
ref#Weathwer_add01038.pcm#Zeff#male#杭州5月20号需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;dayNum=20 month=may;air_quality;口罩
ref#Weathwer_add01039.pcm#Zeff#male#江干区10月1号要不要戴口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#江干区;dayNum=1 month=october;air_quality;口罩
ref#Weathwer_add01040.pcm#Zeff#male#明天去杭州需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;d=1;air_quality;口罩
ref#Weathwer_add01041.pcm#Zeff#male#查一下周三的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=wednesday
ref#Weathwer_add01042.pcm#Zeff#male#上周五天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=friday w=-1
ref#Weathwer_add01043.pcm#Zeff#male#5月20号天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#dayNum=20 month=may
ref#Weathwer_add01044.pcm#Zeff#male#10月1号天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#dayNum=1 month=october
ref#Weathwer_add01045.pcm#Zeff#male#周二的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#weekday=tuesday
ref#Weathwer_add01046.pcm#Zeff#male#周二有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=tuesday;rain;雨
ref#Weathwer_add01047.pcm#Zeff#male#后天有没有雾霾#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=2;air_quality;雾霾
ref#Weathwer_add01048.pcm#Zeff#male#5月20号下不下雨#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=20 month=may;rain;雨
ref#Weathwer_add01049.pcm#Zeff#male#10月1号下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=1 month=october;rain;雨
ref#Weathwer_add01050.pcm#Zeff#male#明天刮风吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=1;wind;刮风
ref#Weathwer_add01051.pcm#Zeff#male#周二要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=tuesday;rain;伞
ref#Weathwer_add01052.pcm#Zeff#male#后天要不要拿伞#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=2;rain;伞
ref#Weathwer_add01053.pcm#Zeff#male#5月20号需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=20 month=may;rain;伞
ref#Weathwer_add01054.pcm#Zeff#male#10月1号要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=1 month=october;rain;伞
ref#Weathwer_add01055.pcm#Zeff#male#明天需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=1;rain;伞
ref#Weathwer_add01056.pcm#Zeff#male#后天要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=2;sunny;墨镜
ref#Weathwer_add01057.pcm#Zeff#male#下周二要不要拿墨镜#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=tuesday w=1;sunny;墨镜
ref#Weathwer_add01058.pcm#Zeff#male#5月20号需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=20 month=may;sunny;墨镜
ref#Weathwer_add01060.pcm#Zeff#male#周五需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=friday;sunny;墨镜
ref#Weathwer_add01061.pcm#Zeff#male#周一要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=monday;air_quality;口罩
ref#Weathwer_add01062.pcm#Zeff#male#后天要不要拿口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=2;air_quality;口罩
ref#Weathwer_add01063.pcm#Zeff#male#5月20号天气怎么样需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=20 month=may;air_quality;口罩
ref#Weathwer_add01064.pcm#Zeff#male#10月1号要不要戴口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=1 month=october;air_quality;口罩
ref#Weathwer_add01065.pcm#Zeff#male#明天需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=1;air_quality;口罩
ref#Weathwer_add01066.pcm#Zeff#male#查一下通州区上周的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#通州区;w=-1
ref#Weathwer_add01067.pcm#Zeff#male#上海徐汇区上周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#上海徐汇区;w=-1
ref#Weathwer_add01068.pcm#Zeff#male#杭州这周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#杭州;w=0
ref#Weathwer_add01069.pcm#Zeff#male#下城区下下周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#下城区;w=2
ref#Weathwer_add01070.pcm#Zeff#male#北京大兴下周的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date#北京大兴;w=1
ref#Weathwer_add01071.pcm#Zeff#male#荔湾区本周二有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#荔湾区;weekday=tuesday w=0;rain;雨
ref#Weathwer_add01072.pcm#Zeff#male#越秀区下周有没有雾霾#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#越秀区;w=1;air_quality;雾霾
ref#Weathwer_add01073.pcm#Zeff#male#杭州上上周下不下雨#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;w=-2;rain;雨
ref#Weathwer_add01074.pcm#Zeff#male#武汉武昌下下周下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#武汉武昌;w=2;rain;雨
ref#Weathwer_add01075.pcm#Zeff#male#枝江市这周刮风吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#枝江市;w=0;windy;刮风
ref#Weathwer_add01076.pcm#Zeff#male#这周去长沙岳麓区要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#长沙岳麓区;w=0;rain;伞
ref#Weathwer_add01077.pcm#Zeff#male#下周去长沙县要不要拿伞#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#长沙县;w=1;rain;伞
ref#Weathwer_add01078.pcm#Zeff#male#上上周去杭州需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;w=-2;rain;伞
ref#Weathwer_add01079.pcm#Zeff#male#下下周去福田区要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#福田区;w=2;rain;伞
ref#Weathwer_add01080.pcm#Zeff#male#本周去崇州市需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#崇州市;rain;伞
ref#Weathwer_add01081.pcm#Zeff#male#这周去玄武区要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#玄武区;w=0;sunny;墨镜
ref#Weathwer_add01082.pcm#Zeff#male#下周去南京要不要拿墨镜#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#南京;w=1;sunny;墨镜
ref#Weathwer_add01083.pcm#Zeff#male#崇明上上周需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#崇明;w=-2;sunny;墨镜
ref#Weathwer_add01084.pcm#Zeff#male#南京鼓楼区下下周要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#南京鼓楼区;w=2;sunny;墨镜
ref#Weathwer_add01085.pcm#Zeff#male#本周去雨花台区需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#雨花台区;w=0;sunny;墨镜
ref#Weathwer_add01086.pcm#Zeff#male#这周去建德要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#建德;w=0;air_quality;口罩
ref#Weathwer_add01087.pcm#Zeff#male#下周去余姚要不要拿口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#余姚;w=1;air_quality;口罩
ref#Weathwer_add01088.pcm#Zeff#male#婺城区上上周天气怎么样需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#婺城区;w=-2;air_quality;口罩
ref#Weathwer_add01089.pcm#Zeff#male#杭州上上周要不要戴口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;w=-2;air_quality;口罩
ref#Weathwer_add01090.pcm#Zeff#male#本周去郑州需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#郑州市;w=0;air_quality;口罩
ref#Weathwer_add01091.pcm#Zeff#male#查一下这周的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#Weathwer_add01092.pcm#Zeff#male#上周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=-1
ref#Weathwer_add01093.pcm#Zeff#male#上上周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=-2
ref#Weathwer_add01094.pcm#Zeff#male#下下周天气怎么样#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=2
ref#Weathwer_add01095.pcm#Zeff#male#本周的天气#INTENT_Apps_Weather_Inquiry#RECOG_SLOT_Main_Date#w=0
ref#Weathwer_add01096.pcm#Zeff#male#这周有雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;rain;雨
ref#Weathwer_add01097.pcm#Zeff#male#下周有没有雾霾#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=1;air_quality;雾霾
ref#Weathwer_add01098.pcm#Zeff#male#上上周下不下雨#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=-2;rain;雨
ref#Weathwer_add01099.pcm#Zeff#male#下下周下雨吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=2;rain;雨
ref#Weathwer_add01100.pcm#Zeff#male#本周刮风吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;windy;风
ref#Weathwer_add01101.pcm#Zeff#male#这周带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;rain;伞
ref#Weathwer_add01102.pcm#Zeff#male#下周要不要拿伞#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=1;rain;伞
ref#Weathwer_add01103.pcm#Zeff#male#上上周需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=-2;rain;伞
ref#Weathwer_add01104.pcm#Zeff#male#下下周要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=2;rain;伞
ref#Weathwer_add01105.pcm#Zeff#male#本周需要带伞吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;rain;伞
ref#Weathwer_add01106.pcm#Zeff#male#下周要带墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=1;sunny;墨镜
ref#Weathwer_add01107.pcm#Zeff#male#上周要不要拿墨镜#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=-1;sunny;墨镜
ref#Weathwer_add01108.pcm#Zeff#male#上上周需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=-2;sunny;墨镜
ref#Weathwer_add01109.pcm#Zeff#male#下下周要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=2;sunny;墨镜
ref#Weathwer_add01110.pcm#Zeff#male#本周需要戴墨镜吗#INTENT_Apps_Weather_InquiryByCondition#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;sunny;墨镜
ref#Weathwer_add01111.pcm#Zeff#male#下周要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=1;air_quality;口罩
ref#Weathwer_add01112.pcm#Zeff#male#这周要不要拿口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;air_quality;口罩
ref#Weathwer_add01113.pcm#Zeff#male#上上周天气怎么样需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=-2;air_quality;口罩
ref#Weathwer_add01114.pcm#Zeff#male#下下周要不要戴口罩#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=2;air_quality;口罩
ref#Weathwer_add01115.pcm#Zeff#male#本周需要戴口罩吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;air_quality;口罩
ref#Weathwer_add01116.pcm#Zeff#male#查下天气#INTENT_Apps_Weather_Inquiry##
ref#Weathwer_add01117.pcm#Zeff#male#我要查天气#INTENT_Apps_Weather_Inquiry##
ref#Weathwer_add01118.pcm#Zeff#male#帮我看看天气预报#INTENT_Apps_Weather_Inquiry##
ref#Weathwer_add01119.pcm#Zeff#male#我想知道天气情况#INTENT_Apps_Weather_Inquiry##
ref#Weathwer_add01120.pcm#Zeff#male#今天适合洗车吗#INTENT_Apps_Weather_InquiryByCarwash#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;carwash_index;洗车
ref#Weathwer_add01121.pcm#Zeff#male#5月25号可以洗车吗#INTENT_Apps_Weather_InquiryByCarwash#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#dayNum=25 month=may;carwash_index;洗车
ref#Weathwer_add01122.pcm#Zeff#male#下下周能洗车吗#INTENT_Apps_Weather_InquiryByCarwash#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=2;carwash_index;洗车
ref#Weathwer_add01123.pcm#Zeff#male#今天适合洗车吗#INTENT_Apps_Weather_InquiryByCarwash#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;carwash_index;洗车
ref#Weathwer_add01124.pcm#Zeff#male#今天能洗车吗#INTENT_Apps_Weather_InquiryByCarwash#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;carwash_index;洗车
ref#Weathwer_add01125.pcm#Zeff#male#今天空气质量怎么样#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;air_quality;空气质量
ref#Weathwer_add01126.pcm#Zeff#male#杭州今天的空气质量#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;d=0;air_quality;空气质量
ref#Weathwer_add01127.pcm#Zeff#male#长宁区5月12号的AQI#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#长宁区;dayNum=12 month=may;air_quality;空气质量
ref#Weathwer_add01128.pcm#Zeff#male#滨江区10月1号的空气质量#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#滨江区;dayNum=1 month=october;air_quality;空气质量
ref#Weathwer_add01129.pcm#Zeff#male#这周五的空气质量好吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#weekday=friday w=0;air_quality;空气质量
ref#Weathwer_add01130.pcm#Zeff#male#今天空气质量咋样#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;air_quality;空气质量
ref#Weathwer_add01131.pcm#Zeff#male#今天的空气质量好吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;air_quality;空气质量
ref#Weathwer_add01132.pcm#Zeff#male#今天的空气质量多少#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;air_quality;空气质量
ref#Weathwer_add01133.pcm#Zeff#male#今天的空气指数多少#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#d=0;air_quality;空气指数
ref#Weathwer_add01134.pcm#Zeff#male#这周空气质量怎么样#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;air_quality;空气质量
ref#Weathwer_add01135.pcm#Zeff#male#杭州下周的空气质量#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;w=1;air_quality;空气质量
ref#Weathwer_add01136.pcm#Zeff#male#长宁区下下周的AQI#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#长宁区;w=2;air_quality;AQI
ref#Weathwer_add01137.pcm#Zeff#male#滨江区上上周的空气质量#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#滨江区;w=-2;air_quality;空气质量
ref#Weathwer_add01138.pcm#Zeff#male#这周的空气质量好吗#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;air_quality;空气质量
ref#Weathwer_add01139.pcm#Zeff#male#这周空气指数怎么样#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#w=0;air_quality;空气指数
ref#Weathwer_add01140.pcm#Zeff#male#杭州下周的空气指数#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#杭州;w=1;air_quality;空气指数
ref#Weathwer_add01141.pcm#Zeff#male#长宁区下下周的空气指数#INTENT_Apps_Weather_InquiryByAQI#RECOG_SLOT_Weather_CityName;RECOG_SLOT_Main_Date;RECOG_SLOT_Weather_Condition;RECOG_SLOT_Weather_Condition_Literal#长宁区;w=2;air_quality;空气指数

