#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#;slotname#;slotvalue
head
ref#Baike_01001.pcm#zhangli#female#你知道包不同吗#INTENT_Apps_Chat_General##
ref#Baike_01002.pcm#zhangli#female#李乐伟是谁呀#INTENT_Apps_Chat_General##
ref#Baike_01003.pcm#zhangli#female#潘又安是谁呀#INTENT_Apps_Chat_General##
ref#Baike_01004.pcm#zhangli#female#谁是娥皇女英#INTENT_Apps_Chat_General##
ref#Baike_01006.pcm#zhangli#female#谁是张果老#INTENT_Apps_Chat_General##
ref#Baike_01007.pcm#zhangli#female#谁是广成子#INTENT_Apps_Chat_General##
ref#Baike_01008.pcm#zhangli#female#扁嘴伦是谁呀#INTENT_Apps_Chat_General##
ref#Baike_01009.pcm#zhangli#female#花泽类是谁啊#INTENT_Apps_Chat_General##
ref#Baike_01010.pcm#zhangli#female#谁是碧霞元君#INTENT_Apps_Chat_General##
ref#Baike_01011.pcm#zhangli#female#你知道曹爽吗#INTENT_Apps_Chat_General##
ref#Baike_01012.pcm#zhangli#female#庚子事变是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01013.pcm#zhangli#female#吴光伟事件是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01014.pcm#zhangli#female#什么是东学党起义#INTENT_Apps_Chat_General##
ref#Baike_01015.pcm#zhangli#female#什么是果敢同盟军#INTENT_Apps_Chat_General##
ref#Baike_01016.pcm#zhangli#female#什么是第三浪潮#INTENT_Apps_Chat_General##
ref#Baike_01017.pcm#zhangli#female#什么是三河镇大捷#INTENT_Apps_Chat_General##
ref#Baike_01018.pcm#zhangli#female#什么是里达暴动#INTENT_Apps_Chat_General##
ref#Baike_01019.pcm#zhangli#female#白马河之战是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01020.pcm#zhangli#female#什么是湘西攻势#INTENT_Apps_Chat_General##
ref#Baike_01021.pcm#zhangli#female#花冈惨案在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01022.pcm#zhangli#female#王桥战斗是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01023.pcm#zhangli#female#什么是樟脑战争#INTENT_Apps_Chat_General##
ref#Baike_01024.pcm#zhangli#female#大跃进是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01025.pcm#zhangli#female#什么是什叶派#INTENT_Apps_Chat_General##
ref#Baike_01026.pcm#zhangli#female#耶稣受难日是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01027.pcm#zhangli#female#白莲教在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01028.pcm#zhangli#female#以色列是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01029.pcm#zhangli#female#十八罗汉是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01030.pcm#zhangli#female#基督山伯爵是谁#INTENT_Apps_Chat_General##
ref#Baike_01031.pcm#zhangli#female#人类古文明发祥地在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01032.pcm#zhangli#female#二里头文化在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01033.pcm#zhangli#female#印度支那战争是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01035.pcm#zhangli#female#司母戊大方鼎是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01036.pcm#zhangli#female#罗密欧与朱丽叶是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01037.pcm#zhangli#female#碟中谍是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01038.pcm#zhangli#female#蒙太奇是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01039.pcm#zhangli#female#爱你一万年是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01040.pcm#zhangli#female#大力水手是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01041.pcm#zhangli#female#卓别林是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01042.pcm#zhangli#female#勇敢的心是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01043.pcm#zhangli#female#美国队长是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01044.pcm#zhangli#female#汗血宝马在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01045.pcm#zhangli#female#皮影戏是什么#INTENT_Apps_Chat_General##
ref#Baike_01046.pcm#zhangli#female#西厢记在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01047.pcm#zhangli#female#富春山居图怎么样#INTENT_Apps_Chat_General##
ref#Baike_01048.pcm#zhangli#female#什么叫拜占庭艺术#INTENT_Apps_Chat_General##
ref#Baike_01049.pcm#zhangli#female#什么叫岁寒三友#INTENT_Apps_Chat_General##
ref#Baike_01050.pcm#zhangli#female#丹霞地貌在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01051.pcm#zhangli#female#喀斯特地形在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01052.pcm#zhangli#female#火山为什么喷发#INTENT_Apps_Chat_General##
ref#Baike_01053.pcm#zhangli#female#夜明珠是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01054.pcm#zhangli#female#花岗岩在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01055.pcm#zhangli#female#什么是玛瑙石#INTENT_Apps_Chat_General##
ref#Baike_01056.pcm#zhangli#female#什么是紫石英#INTENT_Apps_Chat_General##
ref#Baike_01057.pcm#zhangli#female#氧化铁是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01058.pcm#zhangli#female#巴伦支海在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01059.pcm#zhangli#female#贝加尔湖在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01060.pcm#zhangli#female#什么是麦哲伦海峡#INTENT_Apps_Chat_General##
ref#Baike_01061.pcm#zhangli#female#浏阳河在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01062.pcm#zhangli#female#巴拿马运河在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01063.pcm#zhangli#female#圣淘沙在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01064.pcm#zhangli#female#芭提亚是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01065.pcm#zhangli#female#三角洲是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01066.pcm#zhangli#female#莫高窟是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01067.pcm#zhangli#female#未央宫是神马#INTENT_Apps_Chat_General##
ref#Baike_01068.pcm#zhangli#female#大雁塔在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01069.pcm#zhangli#female#太极殿是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01070.pcm#zhangli#female#三星堆是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01071.pcm#zhangli#female#二次元是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01072.pcm#zhangli#female#童养媳是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01073.pcm#zhangli#female#你知道长江三峡吗#INTENT_Apps_Chat_General##
ref#Baike_01074.pcm#zhangli#female#少林寺是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01075.pcm#zhangli#female#大闸蟹是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01076.pcm#zhangli#female#纳木错是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01077.pcm#zhangli#female#玛雅人是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01078.pcm#zhangli#female#日本人是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01079.pcm#zhangli#female#土匪是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01080.pcm#zhangli#female#屌丝是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01081.pcm#zhangli#female#白骨精是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01082.pcm#zhangli#female#码农是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01083.pcm#zhangli#female#你知道注册会计师吗#INTENT_Apps_Chat_General##
ref#Baike_01084.pcm#zhangli#female#元帅是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01085.pcm#zhangli#female#火箭军是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01086.pcm#zhangli#female#外科医生是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01087.pcm#zhangli#female#空姐是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01088.pcm#zhangli#female#正当防卫过当是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01089.pcm#zhangli#female#无罪推定是啥#INTENT_Apps_Chat_General##
ref#Baike_01090.pcm#zhangli#female#剥夺政治权利#INTENT_Apps_Chat_General##
ref#Baike_01091.pcm#zhangli#female#中元节是啥#INTENT_Apps_Chat_General##
ref#Baike_01092.pcm#zhangli#female#雄黄酒是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01093.pcm#zhangli#female#雷峰塔是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01094.pcm#zhangli#female#桃木剑是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01095.pcm#zhangli#female#席梦思是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01096.pcm#zhangli#female#你知道踢脚线吗#INTENT_Apps_Chat_General##
ref#Baike_01097.pcm#zhangli#female#飘窗是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01098.pcm#zhangli#female#遮瑕笔是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01099.pcm#zhangli#female#水泥是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01100.pcm#zhangli#female#瑜伽是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01101.pcm#zhangli#female#九色鹿是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01102.pcm#zhangli#female#圣大保罗是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01103.pcm#zhangli#female#鸿星尔克是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01104.pcm#zhangli#female#安娜苏干什么的#INTENT_Apps_Chat_General##
ref#Baike_01105.pcm#zhangli#female#UGG是干什么的#INTENT_Apps_Chat_General##
ref#Baike_01106.pcm#zhangli#female#肚兜是啥#INTENT_Apps_Chat_General##
ref#Baike_01107.pcm#zhangli#female#平板支撑怎么做#INTENT_Apps_Chat_General##
ref#Baike_01108.pcm#zhangli#female#星际争霸怎么样#INTENT_Apps_Chat_General##
ref#Baike_01109.pcm#zhangli#female#魔兽世界是啥#INTENT_Apps_Chat_General##
ref#Baike_01110.pcm#zhangli#female#什么叫王者荣耀#INTENT_Apps_Chat_General##
ref#Baike_01111.pcm#zhangli#female#DOTA干什么的#INTENT_Apps_Chat_General##
ref#Baike_01112.pcm#zhangli#female#什么叫大菠萝#INTENT_Apps_Chat_General##
ref#Baike_01113.pcm#zhangli#female#蹦极怎么玩#INTENT_Apps_Chat_General##
ref#Baike_01114.pcm#zhangli#female#跑酷怎么玩#INTENT_Apps_Chat_General##
ref#Baike_01115.pcm#zhangli#female#速降怎么玩#INTENT_Apps_Chat_General##
ref#Baike_01116.pcm#zhangli#female#攀岩怎么玩#INTENT_Apps_Chat_General##
ref#Baike_01117.pcm#zhangli#female#什么叫泰拳#INTENT_Apps_Chat_General##
ref#Baike_01118.pcm#zhangli#female#马拉松怎么玩#INTENT_Apps_Chat_General##
ref#Baike_01119.pcm#zhangli#female#花样游泳好玩吗#INTENT_Apps_Chat_General##
ref#Baike_01120.pcm#zhangli#female#泡泡堂是什么#INTENT_Apps_Chat_General##
ref#Baike_01121.pcm#zhangli#female#什么叫人工智能#INTENT_Apps_Chat_General##
ref#Baike_01122.pcm#zhangli#female#什么叫操作系统#INTENT_Apps_Chat_General##
ref#Baike_01123.pcm#zhangli#female#什么叫离散函数#INTENT_Apps_Chat_General##
ref#Baike_01124.pcm#zhangli#female#什么叫傅里叶变换#INTENT_Apps_Chat_General##
ref#Baike_01125.pcm#zhangli#female#绿坝是什么#INTENT_Apps_Chat_General##
ref#Baike_01126.pcm#zhangli#female#QQ是什么#INTENT_Apps_Chat_General##
ref#Baike_01127.pcm#zhangli#female#机顶盒是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01128.pcm#zhangli#female#云计算是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01129.pcm#zhangli#female#什么叫4G#INTENT_Apps_Chat_General##
ref#Baike_01130.pcm#zhangli#female#刷机是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01131.pcm#zhangli#female#宇宙大爆炸是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01132.pcm#zhangli#female#浏览器是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01133.pcm#zhangli#female#九星连珠是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01134.pcm#zhangli#female#流星雨是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01135.pcm#zhangli#female#白羊座是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01136.pcm#zhangli#female#超新星是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01137.pcm#zhangli#female#黑洞是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01138.pcm#zhangli#female#异次元是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01139.pcm#zhangli#female#龙卷风在哪里#INTENT_Apps_Chat_General##
ref#Baike_01140.pcm#zhangli#female#彗星是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01141.pcm#zhangli#female#天王星在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01142.pcm#zhangli#female#水星凌日是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01143.pcm#zhangli#female#台风是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01144.pcm#zhangli#female#你知道美元指数吗#INTENT_Apps_Chat_General##
ref#Baike_01145.pcm#zhangli#female#套利是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01146.pcm#zhangli#female#创业板是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01147.pcm#zhangli#female#套期保值是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01148.pcm#zhangli#female#布林线是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01149.pcm#zhangli#female#超额累进税率是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01150.pcm#zhangli#female#市盈率是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01151.pcm#zhangli#female#绩效管理是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01153.pcm#zhangli#female#供应链怎么解释#INTENT_Apps_Chat_General##
ref#Baike_01154.pcm#zhangli#female#霍桑效应是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01155.pcm#zhangli#female#你知道甘特图吗#INTENT_Apps_Chat_General##
ref#Baike_01156.pcm#zhangli#female#承兑汇票怎么解释#INTENT_Apps_Chat_General##
ref#Baike_01157.pcm#zhangli#female#当铺是怎么回事#INTENT_Apps_Chat_General##
ref#Baike_01158.pcm#zhangli#female#你知道尼安德特人吗#INTENT_Apps_Chat_General##
ref#Baike_01159.pcm#zhangli#female#直立人是谁啊#INTENT_Apps_Chat_General##
ref#Baike_01160.pcm#zhangli#female#金银花能吃吗#INTENT_Apps_Chat_General##
ref#Baike_01161.pcm#zhangli#female#印度人是谁啊#INTENT_Apps_Chat_General##
ref#Baike_01162.pcm#zhangli#female#雅利安人是谁啊#INTENT_Apps_Chat_General##
ref#Baike_01163.pcm#zhangli#female#基因是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01164.pcm#zhangli#female#病毒是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01165.pcm#zhangli#female#青霉素是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01166.pcm#zhangli#female#无花果是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01167.pcm#zhangli#female#火龙果好吃吗#INTENT_Apps_Chat_General##
ref#Baike_01168.pcm#zhangli#female#仙人掌能吃吗#INTENT_Apps_Chat_General##
ref#Baike_01169.pcm#zhangli#female#光合作用怎么解释#INTENT_Apps_Chat_General##
ref#Baike_01170.pcm#zhangli#female#皇冠西大虫是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01171.pcm#zhangli#female#水母是什么意思#INTENT_Apps_Chat_General##
ref#Baike_01172.pcm#zhangli#female#猛犸象是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01173.pcm#zhangli#female#石斑鱼是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01174.pcm#zhangli#female#沙丁鱼在哪里#INTENT_Apps_Chat_General##
ref#Baike_01175.pcm#zhangli#female#狒狒在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01176.pcm#zhangli#female#鸭嘴兽是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01177.pcm#zhangli#female#海豚在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01178.pcm#zhangli#female#壁虎在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01179.pcm#zhangli#female#鹦鹉在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01180.pcm#zhangli#female#企鹅在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01181.pcm#zhangli#female#绵羊在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01182.pcm#zhangli#female#海豹是什么啊#INTENT_Apps_Chat_General##
ref#Baike_01183.pcm#zhangli#female#含羞草在哪儿#INTENT_Apps_Chat_General##
ref#Baike_01184.pcm#zhangli#female#蔷薇能吃吗#INTENT_Apps_Chat_General##
ref#Calculator_01001.pcm#zhangli#female#40+380等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01002.pcm#zhangli#female#5+8减10等于几#INTENT_Apps_Chat_General##
ref#Calculator_01003.pcm#zhangli#female#99乘99#INTENT_Apps_Chat_General##
ref#Calculator_01004.pcm#zhangli#female#7的乘方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01005.pcm#zhangli#female#1+2+3+4+5+6+7+8+9+10+11+12#INTENT_Apps_Chat_General##
ref#Calculator_01006.pcm#zhangli#female#27乘以66等于几#INTENT_Apps_Chat_General##
ref#Calculator_01007.pcm#zhangli#female#999乘以999等于几#INTENT_Apps_Chat_General##
ref#Calculator_01008.pcm#zhangli#female#25的倒数是多少#INTENT_Apps_Chat_General##
ref#Calculator_01009.pcm#zhangli#female#10000乘以20000等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01010.pcm#zhangli#female#5+7等于几#INTENT_Apps_Chat_General##
ref#Calculator_01011.pcm#zhangli#female#0.5+0.5等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01012.pcm#zhangli#female#25开三次方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01013.pcm#zhangli#female#2除以1+0减3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01014.pcm#zhangli#female#13.8的倒数是多少#INTENT_Apps_Chat_General##
ref#Calculator_01015.pcm#zhangli#female#1000乘以200等于几#INTENT_Apps_Chat_General##
ref#Calculator_01016.pcm#zhangli#female#215减去35等于180#INTENT_Apps_Chat_General##
ref#Calculator_01017.pcm#zhangli#female#13的平方是多少#INTENT_Apps_Chat_General##
ref#Calculator_01018.pcm#zhangli#female#35的三次方是多大#INTENT_Apps_Chat_General##
ref#Calculator_01019.pcm#zhangli#female#863乘以796等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01020.pcm#zhangli#female#2的八次方再加1000是多大#INTENT_Apps_Chat_General##
ref#Calculator_01021.pcm#zhangli#female#4乘16是多少#INTENT_Apps_Chat_General##
ref#Calculator_01022.pcm#zhangli#female#100000000再乘以100000000是多大#INTENT_Apps_Chat_General##
ref#Calculator_01023.pcm#zhangli#female#根号2乘以根号3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01024.pcm#zhangli#female#44的平方是多少#INTENT_Apps_Chat_General##
ref#Calculator_01025.pcm#zhangli#female#250乘以250#INTENT_Apps_Chat_General##
ref#Calculator_01026.pcm#zhangli#female#91乘65等于几#INTENT_Apps_Chat_General##
ref#Calculator_01027.pcm#zhangli#female#7的9次方是多少#INTENT_Apps_Chat_General##
ref#Calculator_01028.pcm#zhangli#female#20除以6等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01029.pcm#zhangli#female#74的平方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01030.pcm#zhangli#female#109+1等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01031.pcm#zhangli#female#345的倒数是多少#INTENT_Apps_Chat_General##
ref#Calculator_01032.pcm#zhangli#female#11乘11等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01033.pcm#zhangli#female#根号五等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01034.pcm#zhangli#female#128乘以324等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01035.pcm#zhangli#female#9开方等于几#INTENT_Apps_Chat_General##
ref#Calculator_01036.pcm#zhangli#female#5+3等于几#INTENT_Apps_Chat_General##
ref#Calculator_01037.pcm#zhangli#female#155+555等于几#INTENT_Apps_Chat_General##
ref#Calculator_01038.pcm#zhangli#female#4乘以16等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01039.pcm#zhangli#female#1+12等于几#INTENT_Apps_Chat_General##
ref#Calculator_01040.pcm#zhangli#female#100的100次方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01041.pcm#zhangli#female#10+10等于几#INTENT_Apps_Chat_General##
ref#Calculator_01042.pcm#zhangli#female#6的阶乘是多少#INTENT_Apps_Chat_General##
ref#Calculator_01043.pcm#zhangli#female#8除629#INTENT_Apps_Chat_General##
ref#Calculator_01044.pcm#zhangli#female#10乘以3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01045.pcm#zhangli#female#88除以4等于几#INTENT_Apps_Chat_General##
ref#Calculator_01046.pcm#zhangli#female#80乘以0.04乘以0.03等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01047.pcm#zhangli#female#74开方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01048.pcm#zhangli#female#204乘以378的多少#INTENT_Apps_Chat_General##
ref#Calculator_01049.pcm#zhangli#female#2+3+4+5减6乘以7等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01050.pcm#zhangli#female#9的三次方是多少#INTENT_Apps_Chat_General##
ref#Calculator_01051.pcm#zhangli#female#2的八次方是多少#INTENT_Apps_Chat_General##
ref#Calculator_01052.pcm#zhangli#female#10000乘以1000等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01053.pcm#zhangli#female#8的五次方是多大#INTENT_Apps_Chat_General##
ref#Calculator_01054.pcm#zhangli#female#56乘56等于几#INTENT_Apps_Chat_General##
ref#Calculator_01055.pcm#zhangli#female#1000000乘以1000000是多大#INTENT_Apps_Chat_General##
ref#Calculator_01056.pcm#zhangli#female#1+2+3+8+96等于几#INTENT_Apps_Chat_General##
ref#Calculator_01057.pcm#zhangli#female#4.9+14.9+19.9等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01058.pcm#zhangli#female#根号四乘以三再加上52.6等于几#INTENT_Apps_Chat_General##
ref#Calculator_01059.pcm#zhangli#female#1+2+3+8+96等于几#INTENT_Apps_Chat_General##
ref#Calculator_01060.pcm#zhangli#female#45的倒数是多少#INTENT_Apps_Chat_General##
ref#Calculator_01061.pcm#zhangli#female#1000除以10等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01062.pcm#zhangli#female#5+3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01063.pcm#zhangli#female#99乘以99再除以88#INTENT_Apps_Chat_General##
ref#Calculator_01064.pcm#zhangli#female#根号25等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01065.pcm#zhangli#female#50乘以3=150#INTENT_Apps_Chat_General##
ref#Calculator_01066.pcm#zhangli#female#123乘以346#INTENT_Apps_Chat_General##
ref#Calculator_01067.pcm#zhangli#female#1000除以345等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01068.pcm#zhangli#female#23乘以27等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01069.pcm#zhangli#female#23乘以3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01070.pcm#zhangli#female#100乘100等于几#INTENT_Apps_Chat_General##
ref#Calculator_01071.pcm#zhangli#female#2的三次方乘以2的五次方的结果#INTENT_Apps_Chat_General##
ref#Calculator_01072.pcm#zhangli#female#10000加2000等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01073.pcm#zhangli#female#根号四乘以三再加上52.6等于几#INTENT_Apps_Chat_General##
ref#Calculator_01074.pcm#zhangli#female#170乘以101等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01075.pcm#zhangli#female#1+99等于几#INTENT_Apps_Chat_General##
ref#Calculator_01076.pcm#zhangli#female#12+1等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01077.pcm#zhangli#female#5+5等于几#INTENT_Apps_Chat_General##
ref#Calculator_01078.pcm#zhangli#female#2+6+7减8等于几#INTENT_Apps_Chat_General##
ref#Calculator_01079.pcm#zhangli#female#100除以3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01080.pcm#zhangli#female#91乘以97等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01081.pcm#zhangli#female#3+2乘8等于几#INTENT_Apps_Chat_General##
ref#Calculator_01082.pcm#zhangli#female#35+17等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01083.pcm#zhangli#female#5+3等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01084.pcm#zhangli#female#3减4等于几#INTENT_Apps_Chat_General##
ref#Calculator_01085.pcm#zhangli#female#6乘以9等于几#INTENT_Apps_Chat_General##
ref#Calculator_01086.pcm#zhangli#female#3+12等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01087.pcm#zhangli#female#3乘以7乘以5等于几#INTENT_Apps_Chat_General##
ref#Calculator_01088.pcm#zhangli#female#100开三次方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01089.pcm#zhangli#female#99乘99等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01090.pcm#zhangli#female#185乘以250#INTENT_Apps_Chat_General##
ref#Calculator_01091.pcm#zhangli#female#185乘以250#INTENT_Apps_Chat_General##
ref#Calculator_01092.pcm#zhangli#female#1+3+6+5等多少#INTENT_Apps_Chat_General##
ref#Calculator_01094.pcm#zhangli#female#5的八次方等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01095.pcm#zhangli#female#1+109等于几#INTENT_Apps_Chat_General##
ref#Calculator_01096.pcm#zhangli#female#36+48等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01097.pcm#zhangli#female#56乘以39等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01098.pcm#zhangli#female#3000+100等于多少#INTENT_Apps_Chat_General##
ref#Calculator_01099.pcm#zhangli#female#56除以4得多多少#INTENT_Apps_Chat_General##
ref#Calculator_01100.pcm#zhangli#female#1024的乘方是多少#INTENT_Apps_Chat_General##
ref#Translator_01001.pcm#zhangli#female#甜甜圈用英语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01002.pcm#zhangli#female#甜甜圈在法语里面怎么说呢#INTENT_Apps_Chat_General##
ref#Translator_01003.pcm#zhangli#female#用德语说潜水艇#INTENT_Apps_Chat_General##
ref#Translator_01004.pcm#zhangli#female#向日葵用瑞典语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01005.pcm#zhangli#female#三文鱼在日语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01006.pcm#zhangli#female#兴高采烈用韩语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01007.pcm#zhangli#female#用西班牙语说我好累啊#INTENT_Apps_Chat_General##
ref#Translator_01008.pcm#zhangli#female#用阿拉伯语说我要吃饭#INTENT_Apps_Chat_General##
ref#Translator_01009.pcm#zhangli#female#把青霉素翻译成保加利亚语#INTENT_Apps_Chat_General##
ref#Translator_01010.pcm#zhangli#female#机关枪在捷克语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01011.pcm#zhangli#female#服务器用丹麦语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01012.pcm#zhangli#female#天王星在希腊语里面叫什么#INTENT_Apps_Chat_General##
ref#Translator_01013.pcm#zhangli#female#电视剧用爱沙尼亚语怎么说呢#INTENT_Apps_Chat_General##
ref#Translator_01014.pcm#zhangli#female#电吹风用芬兰语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01015.pcm#zhangli#female#用匈牙利语说西兰花#INTENT_Apps_Chat_General##
ref#Translator_01016.pcm#zhangli#female#用意大利语说三叉神经#INTENT_Apps_Chat_General##
ref#Translator_01017.pcm#zhangli#female#医院在荷兰语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01018.pcm#zhangli#female#北极熊用波兰语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01019.pcm#zhangli#female#草莓在葡萄牙语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01020.pcm#zhangli#female#用罗马尼亚语说自行车#INTENT_Apps_Chat_General##
ref#Translator_01021.pcm#zhangli#female#用俄语说伏特加酒#INTENT_Apps_Chat_General##
ref#Translator_01022.pcm#zhangli#female#企鹅在斯洛文尼亚语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01023.pcm#zhangli#female#我要吃海鲜在泰语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01024.pcm#zhangli#female#用粤语说今天发工资#INTENT_Apps_Chat_General##
ref#Translator_01025.pcm#zhangli#female#冰淇淋在英语里面怎么说呢#INTENT_Apps_Chat_General##
ref#Translator_01026.pcm#zhangli#female#用法语说计算机#INTENT_Apps_Chat_General##
ref#Translator_01027.pcm#zhangli#female#用德语说水电费#INTENT_Apps_Chat_General##
ref#Translator_01028.pcm#zhangli#female#我想睡觉用瑞典语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01029.pcm#zhangli#female#用日语怎么说我饿了#INTENT_Apps_Chat_General##
ref#Translator_01030.pcm#zhangli#female#用韩语说奥运会#INTENT_Apps_Chat_General##
ref#Translator_01031.pcm#zhangli#female#踢足球用西班牙语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01032.pcm#zhangli#female#用阿拉伯语翻译商业贷款#INTENT_Apps_Chat_General##
ref#Translator_01033.pcm#zhangli#female#把股票翻译成保加利亚语#INTENT_Apps_Chat_General##
ref#Translator_01034.pcm#zhangli#female#把倾盆大雨翻译成捷克语#INTENT_Apps_Chat_General##
ref#Translator_01035.pcm#zhangli#female#丹麦语里面怎么说烤面包#INTENT_Apps_Chat_General##
ref#Translator_01036.pcm#zhangli#female#把航空母舰翻译成希腊语#INTENT_Apps_Chat_General##
ref#Translator_01037.pcm#zhangli#female#把番茄炒鸡蛋翻译成爱沙尼亚语#INTENT_Apps_Chat_General##
ref#Translator_01038.pcm#zhangli#female#把猕猴桃翻译成芬兰语#INTENT_Apps_Chat_General##
ref#Translator_01039.pcm#zhangli#female#匈牙利语怎么说玫瑰花#INTENT_Apps_Chat_General##
ref#Translator_01040.pcm#zhangli#female#意大利语怎么说披萨#INTENT_Apps_Chat_General##
ref#Translator_01041.pcm#zhangli#female#荷兰语怎么说长颈鹿#INTENT_Apps_Chat_General##
ref#Translator_01042.pcm#zhangli#female#波兰语怎么说天鹅#INTENT_Apps_Chat_General##
ref#Translator_01043.pcm#zhangli#female#把猫头鹰翻译成葡萄牙语呢#INTENT_Apps_Chat_General##
ref#Translator_01044.pcm#zhangli#female#把斑马翻译成罗马尼亚语呢#INTENT_Apps_Chat_General##
ref#Translator_01045.pcm#zhangli#female#宇宙飞船用俄语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01046.pcm#zhangli#female#那斯洛文尼亚语呢#INTENT_Apps_Chat_General##
ref#Translator_01047.pcm#zhangli#female#那泰语怎么说水龙头#INTENT_Apps_Chat_General##
ref#Translator_01048.pcm#zhangli#female#电灯泡用粤语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01049.pcm#zhangli#female#我要翻译#INTENT_Apps_Chat_General##
ref#Translator_01050.pcm#zhangli#female#双鱼座用英语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01051.pcm#zhangli#female#那法语怎么说龙卷风#INTENT_Apps_Chat_General##
ref#Translator_01052.pcm#zhangli#female#那德语怎么说太阳#INTENT_Apps_Chat_General##
ref#Translator_01053.pcm#zhangli#female#用瑞典语说氧化铁#INTENT_Apps_Chat_General##
ref#Translator_01054.pcm#zhangli#female#用日语说二氧化碳#INTENT_Apps_Chat_General##
ref#Translator_01055.pcm#zhangli#female#那韩语怎么说热水器#INTENT_Apps_Chat_General##
ref#Translator_01056.pcm#zhangli#female#那西班牙语呢#INTENT_Apps_Chat_General##
ref#Translator_01057.pcm#zhangli#female#用阿拉伯语说马拉松#INTENT_Apps_Chat_General##
ref#Translator_01058.pcm#zhangli#female#百货商店用保加利亚语怎么说呢#INTENT_Apps_Chat_General##
ref#Translator_01059.pcm#zhangli#female#甘特图在捷克语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01060.pcm#zhangli#female#把胡萝卜翻译成丹麦语呢#INTENT_Apps_Chat_General##
ref#Translator_01061.pcm#zhangli#female#那希腊语怎么说电饭锅#INTENT_Apps_Chat_General##
ref#Translator_01062.pcm#zhangli#female#望远镜在爱沙尼亚语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01063.pcm#zhangli#female#用芬兰语说猛犸象#INTENT_Apps_Chat_General##
ref#Translator_01064.pcm#zhangli#female#烟灰缸在匈牙利语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01065.pcm#zhangli#female#那意大利语怎么说雨伞#INTENT_Apps_Chat_General##
ref#Translator_01066.pcm#zhangli#female#那荷兰语怎么说蜜蜂#INTENT_Apps_Chat_General##
ref#Translator_01067.pcm#zhangli#female#那波兰语怎么表达说我想喝一杯白兰地#INTENT_Apps_Chat_General##
ref#Translator_01068.pcm#zhangli#female#葡萄酒在葡萄牙语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01069.pcm#zhangli#female#那罗马尼亚语呢#INTENT_Apps_Chat_General##
ref#Translator_01070.pcm#zhangli#female#那俄语怎么说移动互联网#INTENT_Apps_Chat_General##
ref#Translator_01071.pcm#zhangli#female#那斯洛文尼亚语呢#INTENT_Apps_Chat_General##
ref#Translator_01072.pcm#zhangli#female#我的手机掉了怎么翻译成泰语#INTENT_Apps_Chat_General##
ref#Translator_01073.pcm#zhangli#female#我的钱包被偷了怎么翻译成粤语#INTENT_Apps_Chat_General##
ref#Translator_01074.pcm#zhangli#female#我要翻译#INTENT_Apps_Chat_General##
ref#Translator_01075.pcm#zhangli#female#今天我喝了两杯葡萄酒翻译成英语#INTENT_Apps_Chat_General##
ref#Translator_01076.pcm#zhangli#female#大白菜在法语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01077.pcm#zhangli#female#用德语说动手术#INTENT_Apps_Chat_General##
ref#Translator_01078.pcm#zhangli#female#把自来水翻译成瑞典语呢#INTENT_Apps_Chat_General##
ref#Translator_01079.pcm#zhangli#female#用日语说无花果#INTENT_Apps_Chat_General##
ref#Translator_01080.pcm#zhangli#female#高速公路在韩语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01081.pcm#zhangli#female#把龙卷风翻译成西班牙语呢#INTENT_Apps_Chat_General##
ref#Translator_01082.pcm#zhangli#female#用阿拉伯语说方向盘#INTENT_Apps_Chat_General##
ref#Translator_01083.pcm#zhangli#female#用保加利亚语说红茶#INTENT_Apps_Chat_General##
ref#Translator_01084.pcm#zhangli#female#方便面在捷克语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01085.pcm#zhangli#female#金枪鱼在丹麦语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01086.pcm#zhangli#female#电饭锅在希腊语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01087.pcm#zhangli#female#用爱沙尼亚语说花样游泳#INTENT_Apps_Chat_General##
ref#Translator_01088.pcm#zhangli#female#用芬兰语说垃圾桶#INTENT_Apps_Chat_General##
ref#Translator_01089.pcm#zhangli#female#用匈牙利语说睫毛膏#INTENT_Apps_Chat_General##
ref#Translator_01090.pcm#zhangli#female#用意大利语说洗发水#INTENT_Apps_Chat_General##
ref#Translator_01091.pcm#zhangli#female#离散函数用荷兰语怎么说#INTENT_Apps_Chat_General##
ref#Translator_01092.pcm#zhangli#female#用波兰语说洗衣机#INTENT_Apps_Chat_General##
ref#Translator_01093.pcm#zhangli#female#把高利贷翻译成葡萄牙语#INTENT_Apps_Chat_General##
ref#Translator_01094.pcm#zhangli#female#把大闸蟹翻译成罗马尼亚语#INTENT_Apps_Chat_General##
ref#Translator_01095.pcm#zhangli#female#用俄语来翻译实习生#INTENT_Apps_Chat_General##
ref#Translator_01096.pcm#zhangli#female#把杂货铺翻译成斯洛文尼亚语呢#INTENT_Apps_Chat_General##
ref#Translator_01097.pcm#zhangli#female#芭提亚在泰语里面怎么说#INTENT_Apps_Chat_General##
ref#Translator_01098.pcm#zhangli#female#用粤语说体温计#INTENT_Apps_Chat_General##
ref#Translator_01099.pcm#zhangli#female#用日语说天黑请闭眼#INTENT_Apps_Chat_General##
ref#Translator_01100.pcm#zhangli#female#月黑风高在匈牙利语里面怎么说#INTENT_Apps_Chat_General##
ref#Joke_01001.pcm#zhangli#female#来一个笑话#INTENT_Apps_Chat_General##
ref#Joke_01002.pcm#zhangli#female#不好笑呢再来一个#INTENT_Apps_Chat_General##
ref#Joke_01004.pcm#zhangli#female#讲一个日本首相的笑话#INTENT_Apps_Chat_General##
ref#Joke_01005.pcm#zhangli#female#来一个日本人的笑话#INTENT_Apps_Chat_General##
ref#Joke_01006.pcm#zhangli#female#说一个法国人的笑话#INTENT_Apps_Chat_General##
ref#Joke_01007.pcm#zhangli#female#有没有俄罗斯人的笑话#INTENT_Apps_Chat_General##
ref#Joke_01009.pcm#zhangli#female#讲一个欧洲人的笑话#INTENT_Apps_Chat_General##
ref#Joke_01010.pcm#zhangli#female#再说一个笑话#INTENT_Apps_Chat_General##
ref#Joke_01011.pcm#zhangli#female#说一个政治笑话#INTENT_Apps_Chat_General##
ref#Joke_01012.pcm#zhangli#female#来一个跟英国人有关的笑话#INTENT_Apps_Chat_General##
ref#Joke_01013.pcm#zhangli#female#有没有台湾人的笑话#INTENT_Apps_Chat_General##
ref#Joke_01014.pcm#zhangli#female#讲一个蔡英文的笑话#INTENT_Apps_Chat_General##
ref#Joke_01015.pcm#zhangli#female#说个跟包子相关的笑话#INTENT_Apps_Chat_General##
ref#Joke_01016.pcm#zhangli#female#讲一个冷笑话吧#INTENT_Apps_Chat_General##
ref#yanhui_Apps_Chat_InquireCarRest_p0001001.pcm#2#female#今天汽车尾号限行是多少#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#yanhui_Apps_Chat_InquireCarRest_p0001003.pcm#2#female#今天北京汽车尾号限行是多少#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date;RECOG_SLOT_Traffic_CityName#;北京
ref#yanhui_Apps_Chat_InquireCarRest_p0001005.pcm#2#female#明天汽车尾号限行情况#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#yanhui_Apps_Chat_InquireCarRest_p0001006.pcm#2#female#后天成都汽车尾号限行情况#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date;RECOG_SLOT_Traffic_CityName#;成都
ref#yanhui_Apps_Chat_InquireCarRest_p0001007.pcm#2#female#今明两天长沙汽车尾号限行分别是多少#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date;RECOG_SLOT_Traffic_CityName#;长沙
ref#yanhui_Apps_Chat_InquireCarRest_p0001008.pcm#2#female#这周一到周五汽车尾号限行情况#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#yanhui_Apps_Chat_InquireCarRest_p0001009.pcm#2#female#成都周末汽车尾号限行情况#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date;RECOG_SLOT_Traffic_CityName#;成都
ref#yanhui_Apps_Chat_InquireCarViolation_p0001001.pcm#4#female#最近有违章记录吗#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001002.pcm#4#female#查询最近违章记录#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001003.pcm#4#female#最近一周有违章记录吗#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001004.pcm#4#female#查询最近一个月的违章记录#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001005.pcm#4#female#最近我有违章吗#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001006.pcm#4#female#帮我查一下最近的违章记录#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001007.pcm#4#female#我想要查询最近两周的违章记录#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001008.pcm#4#female#最近的违章记录能帮我查询一下吗#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquireCarViolation_p0001009.pcm#4#female#上个月的违章记录帮我显示一下#INTENT_Traffic_InquireCarViolation##
ref#yanhui_Apps_Chat_InquirePlateNumBelong_p0001002.pcm#5#female#川A的归属地是哪#INTENT_Apps_Chat_General##
ref#yanhui_Apps_Chat_InquirePlateNumBelong_p0001003.pcm#5#female#帮我查询湘K的汽车归属地#INTENT_Apps_Chat_General##
ref#252c966895a34298_tts.wav#tts#female#鸡血石是怎么回事#INTENT_Apps_Chat_General##
ref#64d7bac914f45c3b_tts.wav#tts#female#讲一个特朗普的笑话#INTENT_Apps_Chat_General##
ref#de271de08e3ef72a_tts.wav#tts#female#有没有韩国人的笑话#INTENT_Apps_Chat_General##
ref#d7d82f7816e3a622_tts.wav#tts#female#汽车尾号2今天限行吗#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#df2b21b23a31a6b5_tts.wav#tts#female#汽车尾号5哪天限行#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#d6c6b2df65a2f340_tts.wav#tts#female#汽车尾号3和6明天限行吗#INTENT_Traffic_InquireCarRestriction#RECOG_SLOT_Traffic_Date#
ref#dd53cbcfe0eb8780_tts.wav#tts#female#我要查询近一年的违章记录#INTENT_Traffic_InquireCarViolation##
ref#f457922e8345fc59_tts.wav#tts#female#浙A的归属地#INTENT_Apps_Chat_General##
ref#a6957b2baf66395d_tts.wav#tts#female#我想查一下鄂A的归属地#INTENT_Apps_Chat_General##
ref#26202d79a6b16d16_tts.wav#tts#female#浙C的归属地帮我查一下#INTENT_Apps_Chat_General##
ref#2b9f58625572f6a5_tts.wav#tts#female#我要查询沪A的归属地#INTENT_Apps_Chat_General##
ref#2171e6949bcce283_tts.wav#tts#female#黑B的归属地查询#INTENT_Apps_Chat_General##
ref#864d2b9aed17d4c6_tts.wav#tts#female#查询粤Z的归属地#INTENT_Apps_Chat_General##
ref#7bf5b6b69cb35b5b_tts.wav#tts#female#新C的归属地#INTENT_Apps_Chat_General##
ref#487a3ffb802a5753_tts.wav#tts#female#喷火龙是谁呀#INTENT_Apps_Chat_General##
ref#332ca4e48863511b_tts.wav#tts#female#帕金森定律是什么意思#INTENT_Apps_Chat_General##
ref#172c5257133aab95_tts.wav#tts#female#12的四次方等于多少#INTENT_Apps_Chat_General##
ref#fd25be7f51c8f36b_tts.wav#tts#female#查一下京A的归属地在哪里#INTENT_Apps_Chat_General##
