#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#;slotname#;slotvalue
head
ref#News01001.pcm#zhanglei#female#来点新闻#INTENT_Apps_News_TurnOn##
ref#News01002.pcm#zhanglei#female#最近发生的新鲜事#INTENT_Apps_News_TurnOn##
ref#News01003.pcm#zhanglei#female#我想听新闻#INTENT_Apps_News_TurnOn##
ref#News01004.pcm#zhanglei#female#最近有什么新鲜事#INTENT_Apps_News_TurnOn##
ref#News01005.pcm#zhanglei#female#听新闻#INTENT_Apps_News_TurnOn##
ref#News01006.pcm#zhanglei#female#我要知道今天的新闻#INTENT_Apps_News_TurnOn##
ref#News01007.pcm#zhanglei#female#帮我播新闻#INTENT_Apps_News_TurnOn##
ref#News01008.pcm#zhanglei#female#给我播报新闻#INTENT_Apps_News_TurnOn##
ref#News01009.pcm#zhanglei#female#最近有什么新闻#INTENT_Apps_News_TurnOn##
ref#News01010.pcm#zhanglei#female#最近的八卦听一下#INTENT_Apps_News_TurnOn##
ref#News01011.pcm#zhanglei#female#今天有什么新闻八卦#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#八卦
ref#News01012.pcm#zhanglei#female#我想知道今天的娱乐新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#娱乐
ref#News01013.pcm#zhanglei#female#头条新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#News01014.pcm#zhanglei#female#今天的头条是什么#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#News01015.pcm#zhanglei#female#来点新闻八卦听听#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#八卦
ref#NCS_News_01018.pcm#1#male#我要听新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01036.pcm#1#male#中国有什么新闻呀#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#中国
ref#NCS_News_01037.pcm#1#male#最近有什么新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01039.pcm#1#male#有什么新闻啊现在#INTENT_Apps_News_TurnOn##
ref#NCS_News_01040.pcm#1#male#有没有新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01042.pcm#1#male#要听新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01043.pcm#1#male#我要新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01044.pcm#1#male#我要听资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01045.pcm#1#male#我要听最新的新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01046.pcm#1#male#听听新闻吧#INTENT_Apps_News_TurnOn##
ref#NCS_News_01047.pcm#1#male#我听听新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01049.pcm#1#male#说一下新闻吧#INTENT_Apps_News_TurnOn##
ref#NCS_News_01050.pcm#1#male#请播放资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01051.pcm#1#male#念一段新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01052.pcm#1#male#请播国际新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#国际
ref#NCS_News_01053.pcm#1#male#那今天又有什么头条新闻啊#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#NCS_News_01056.pcm#1#male#今天有什么新新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01058.pcm#1#male#今天的新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01062.pcm#1#male#放新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01063.pcm#1#male#查一下今天的新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01064.pcm#1#male#播一个新闻资讯#INTENT_Apps_News_TurnOn##
ref#NCS_News_01066.pcm#1#male#新闻播报#INTENT_Apps_News_TurnOn##
ref#NCS_News_01067.pcm#1#male#新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01068.pcm#1#male#实时新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01072.pcm#1#male#你会讲什么新闻啊#INTENT_Apps_Chat_General##
ref#NCS_News_01081.pcm#1#male#昨天有意思新闻和资讯有哪些#INTENT_Apps_News_TurnOn##
ref#NCS_News_01082.pcm#1#male#昨天有意思新闻和资讯有什么#INTENT_Apps_News_TurnOn##
ref#News01047.pcm#zhanglei#female#我想听财经新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#财经
ref#News_add01001.pcm#zhanglei#female#我要听头条新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#News_add01002.pcm#zhanglei#female#听听娱乐新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#娱乐
ref#News_add01003.pcm#zhanglei#female#播放体育新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#体育
ref#News_add01004.pcm#zhanglei#female#给我搜一下科技相关的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#科技
ref#News_add01005.pcm#zhanglei#female#播点数码新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#数码
ref#News_add01007.pcm#zhanglei#female#我想听军事新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#军事
ref#News_add01008.pcm#zhanglei#female#最近的旅游新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#旅游
ref#News_add01009.pcm#zhanglei#female#搜索一下时尚新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#时尚
ref#NCS_News_01001.pcm#1#male#我想听体育新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#体育
ref#NCS_News_01002.pcm#1#male#我想听新闻要闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#要闻
ref#NCS_News_01004.pcm#1#male#我想听财经新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#财经
ref#NCS_News_01005.pcm#1#male#我想听九寨沟的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#九寨沟
ref#NCS_News_01006.pcm#1#male#我想听新闻摘要#INTENT_Apps_News_TurnOn##
ref#NCS_News_01007.pcm#1#male#我想听刘德华的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#刘德华
ref#NCS_News_01008.pcm#1#male#我想听有关余额宝的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#余额宝
ref#NCS_News_01009.pcm#1#male#我想听爆炸新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#爆炸
ref#NCS_News_01010.pcm#1#male#我想听科技新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#科技
ref#NCS_News_01019.pcm#1#male#我想看财经新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#财经
ref#NCS_News_01020.pcm#1#male#播报国际要闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#国际要闻
ref#NCS_News_01021.pcm#1#male#播放新闻要闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#要闻
ref#NCS_News_01023.pcm#1#male#播放科技新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#科技
ref#NCS_News_01024.pcm#1#male#播放本地新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#本地
ref#NCS_News_01025.pcm#1#male#播报头条新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#NCS_News_01027.pcm#1#male#我要听热点新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#热点
ref#NCS_News_01028.pcm#1#male#我要听八卦新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#八卦
ref#NCS_News_01029.pcm#1#male#我想听娱乐新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#娱乐
ref#NCS_News_01030.pcm#1#male#播报军事新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#军事
ref#NCS_News_01033.pcm#1#male#成都本地今天有什么新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#成都本地
ref#NCS_News_01034.pcm#1#male#播报交通新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#交通
ref#NCS_News_01035.pcm#1#male#昨天有什么重大新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#重大
ref#NCS_News_01038.pcm#1#male#再来一个新闻#INTENT_Apps_News_TurnOn##
ref#NCS_News_01041.pcm#1#male#有没有今天的头条新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#头条
ref#NCS_News_01048.pcm#1#male#说一下范冰冰的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#范冰冰
ref#NCS_News_01054.pcm#1#male#来点焦点新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#焦点
ref#NCS_News_01055.pcm#1#male#今天长春的新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#长春
ref#NCS_News_01057.pcm#1#male#今天体育新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#体育
ref#NCS_News_01059.pcm#1#male#讲腾讯新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#腾讯
ref#NCS_News_01060.pcm#1#male#讲莆田系新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#莆田系
ref#NCS_News_01061.pcm#1#male#给我讲讲一些娱乐新闻吧#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#娱乐
ref#NCS_News_01065.pcm#1#male#报一下时事新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#时事
ref#NCS_News_01070.pcm#1#male#时事新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#时事
ref#NCS_News_01078.pcm#1#male#北京新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#北京
ref#NCS_News_01080.pcm#1#male#最近两天有些什么比较有意思的娱乐方面的新闻和资讯#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#娱乐
ref#6ff7aea459181c7c_tts.wav#tts#female#来点儿社会新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#社会
ref#d91d55ebf5a7ccf4_tts.wav#tts#female#我想看国际新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#国际
ref#79e27241f31a993d_tts.wav#tts#female#播报财经新闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#财经
ref#4d45b994b85d469e_tts.wav#tts#female#播报时政要闻#INTENT_Apps_News_FindByKeyword#RECOG_SLOT_News_Keyword#时政
ref#e36ab710f78881f9_tts.wav#tts#female#你会不会讲新闻#INTENT_Apps_Chat_General##
ref#a2dcd44c4836afb4_tts.wav#tts#female#新闻和咨询#INTENT_Apps_News_TurnOn##
