#head;hrl;2.0;utf-8
#ref#speechfile#speaker#gender#reference word sequence#topic#;slotname#;slotvalue
head
ref#13cce4f245b7ee8a_tts_Hotel.pcm#tts#female#酒店#INTENT_Nav_Hotel_Inquire##
ref#a85148ea24dccc52_tts_Hotel.pcm#tts#female#宾馆#INTENT_Nav_Hotel_Inquire##
ref#f7c04f54816958c4_tts_Hotel.pcm#tts#female#我困了#INTENT_Nav_Hotel_Inquire##
ref#4bca72e22b5b1126_tts_Hotel.pcm#tts#female#我太累了#INTENT_Nav_Hotel_Inquire##
ref#6756f5aa22cf36ca_tts_Hotel.pcm#tts#female#我想睡觉#INTENT_Nav_Hotel_Inquire##
ref#97b93cdab9d3b8eb_tts_Hotel.pcm#tts#female#帮我找家酒店#INTENT_Nav_Hotel_Inquire##
ref#7b3e9f8dc687d4eb_tts_Hotel.pcm#tts#female#我要找酒店#INTENT_Nav_Hotel_Inquire##
ref#397cf28d4e691d47_tts_Hotel.pcm#tts#female#我想找宾馆#INTENT_Nav_Hotel_Inquire##
ref#e1f9ce52a69e4746_tts_Hotel.pcm#tts#female#帮我找一家宾馆#INTENT_Nav_Hotel_Inquire##
ref#79103eec739f7ccb_tts_Hotel.pcm#tts#female#找家酒店住一晚#INTENT_Nav_Hotel_Inquire##
ref#70ed59dea8ed8889_tts_Hotel.pcm#tts#female#查一下酒店#INTENT_Nav_Hotel_Inquire##
ref#2ef1f875e45c2955_tts_Hotel.pcm#tts#female#附近的酒店#INTENT_Nav_Hotel_Inquire##
ref#dd9fa9faddc9f3a9_tts_Hotel.pcm#tts#female#附近的宾馆#INTENT_Nav_Hotel_Inquire##
ref#1c3767bfd2eacb77_tts_Hotel.pcm#tts#female#查询附近的酒店#INTENT_Nav_Hotel_Inquire##
ref#ef3452e3859d0ef3_tts_Hotel.pcm#tts#female#找一下附近有什么住的地方#INTENT_Nav_Hotel_Inquire##
ref#3a58d9b8a8ceecd3_tts_Hotel.pcm#tts#female#帮我找最近的宾馆#INTENT_Nav_Hotel_Inquire##
ref#7fdcc989e6dd8ef7_tts_Hotel.pcm#tts#female#找找看离我最近的酒店#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase1_p0001039.pcm#2#female#有什么住宿的地方#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase1_p0001040.pcm#2#female#晚上能住哪里#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase1_p0001041.pcm#2#female#我想睡觉#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase1_p0001042.pcm#2#female#帮我找个#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001065.pcm#2#female#找个地方过夜#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001066.pcm#2#female#今晚睡哪#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001067.pcm#2#female#我在找旅店#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001068.pcm#2#female#找个#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001069.pcm#2#female#哪里有#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001070.pcm#2#female#我在找#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001071.pcm#2#female#找个#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001072.pcm#2#female#哪里有#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001073.pcm#2#female#我在找旅馆#INTENT_Nav_Hotel_Inquire##旅馆
ref#bmw_phrase3_p0001074.pcm#2#female#找个旅馆#INTENT_Nav_Hotel_Inquire##旅馆
ref#bmw_phrase3_p0001075.pcm#2#female#哪里有旅馆#INTENT_Nav_Hotel_Inquire##旅馆
ref#bmw_phrase3_p0001076.pcm#2#female#我觉得好累啊#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001077.pcm#2#female#感觉有点累#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001078.pcm#2#female#好困啊#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001079.pcm#2#female#感觉有点困#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001080.pcm#2#female#感觉好疲惫啊#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001081.pcm#2#female#有点疲惫#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001082.pcm#2#female#有点累了#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001083.pcm#2#female#有点困了#INTENT_Nav_Hotel_Inquire##
ref#bmw_phrase3_p0001084.pcm#2#female#有点疲倦了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_001.pcm#1#female#帮我找个地方过夜#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_002.pcm#1#female#帮我找个旅社休息下#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_003.pcm#1#female#带我去开房#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_004.pcm#1#female#导航到宾馆#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_005.pcm#1#female#好困啊#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_006.pcm#1#female#好累呀#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_007.pcm#1#female#开个房#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_008.pcm#1#female#困了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_009.pcm#1#female#累了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_010.pcm#1#female#哪里有可以睡觉的地方#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_011.pcm#1#female#去宾馆#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_012.pcm#1#female#去睡觉#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_013.pcm#1#female#我好困#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_014.pcm#1#female#我困了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_015.pcm#1#female#我累了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_016.pcm#1#female#我疲倦了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_017.pcm#1#female#我想睡觉#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_018.pcm#1#female#我想睡觉了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_019.pcm#1#female#我想休息#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_020.pcm#1#female#我想找个地方睡觉#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_021.pcm#1#female#我需要休息的场所#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_022.pcm#1#female#我在外地太累了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_023.pcm#1#female#想找个旅馆#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_024.pcm#1#female#需要睡觉#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_025.pcm#1#female#有点困了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_026.pcm#1#female#有点想睡觉了#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_027.pcm#1#female#找个地方睡觉#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_028.pcm#1#female#找个地方休息#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_029.pcm#1#female#找个旅馆过夜#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_030.pcm#1#female#找个旅馆休息#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_031.pcm#1#female#找个睡觉的地方#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_032.pcm#1#female#找个休息场所#INTENT_Nav_Hotel_Inquire##
ref#Implicit_hotel_034.pcm#1#female#好累啊#INTENT_Nav_Hotel_Inquire##
ref#Implicit_add01053.pcm#zhanglei#female#我要住宿#INTENT_Nav_Hotel_Inquire##
ref#c16f8184d2c0e9fd_tts_Hotel.pcm#tts#female#查找吉利大厦周边的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location#吉利大厦
ref#f4a651a8120f9a16_tts_Hotel.pcm#tts#female#武林广场附近有什么酒店吗#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location#武林广场
ref#b9928c7055c0dac1_tts_Hotel.pcm#tts#female#星耀城旁边的三星级以上的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal#星耀城;3;三星级
ref#3bba2a196e649a03_tts_Hotel.pcm#tts#female#查一下人民广场附近的如家酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Category_Literal#人民广场;如家酒店
ref#fbdf406b70502b8a_tts_Hotel.pcm#tts#female#查找附近的七天酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#七天酒店
ref#1860db96be818ec2_tts_Hotel.pcm#tts#female#我要去99公寓式酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#99公寓式酒店
ref#b62a415be1b8432a_tts_Hotel.pcm#tts#female#去最近的万豪酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#万豪酒店
ref#8597d181b577618b_tts_Hotel.pcm#tts#female#离杭州印最近的希尔顿酒店在哪#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Category_Literal#杭州印;希尔顿酒店
ref#c56835c245a626ae_tts_Hotel.pcm#tts#female#导航到红塔豪华精选酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#红塔豪华精选酒店
ref#c495c868f2a111b5_tts_Hotel.pcm#tts#female#带我到锦江之星杭州西湖大道店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#锦江之星杭州西湖大道店
ref#76fde3f75a1c3d61_tts_Hotel.pcm#tts#female#帮我查找杭州东站周围的五星级酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal#杭州东站;5;五星级
ref#ca96a472393bc1bd_tts_Hotel.pcm#tts#female#找一家价格500元以下的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_PriceMax#500元
ref#a68a355bf5156f85_tts_Hotel.pcm#tts#female#帮我查询价格在500元到1000元的五星级酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal;RECOG_SLOT_Hotel_PriceMax;RECOG_SLOT_Hotel_PriceMin#5;五星级;1000元;500元
ref#c1aeb02b2949e683_tts.wav#tts#female#帮我查询星耀城附近一公里的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Distance;RECOG_SLOT_Hotel_Distance_Literal#三星级;1;一公里
ref#b74c54edb50f73b4_tts.wav#tts#female#中山公园附近三公里内四星级以上的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Distance;RECOG_SLOT_Hotel_Distance_Literal;RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal#中山公园;3;三公里内;4;四星级
ref#78141eda8afb72c3_tts.wav#tts#female#找一家距离江陵路地铁站两公里内的800元以下的四星级以上的酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Distance;RECOG_SLOT_Hotel_Distance_Literal;RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal;RECOG_SLOT_Hotel_PriceMax#江陵路地铁站;2;两公里内;4;四星级;800元
ref#85e264338f9edbd9_tts.wav#tts#female#查找湖滨银泰附近一公里内价格400到900之间的五星级酒店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Location;RECOG_SLOT_Hotel_Distance;RECOG_SLOT_Hotel_Distance_Literal;RECOG_SLOT_Hotel_Category;RECOG_SLOT_Hotel_Category_Literal;RECOG_SLOT_Hotel_PriceMax;RECOG_SLOT_Hotel_PriceMin#湖滨银泰;1;一公里内;5;五星级;900;400
ref#eb9d93eb70a3fcc7_tts.wav#tts#female#我有点困了#INTENT_Nav_Hotel_Inquire##
ref#476a74a53c4b347b_tts.wav#tts#female#找个休息的地儿#INTENT_Nav_Hotel_Inquire##
ref#12d9832f3ae0158d_tts.wav#tts#female#我要休息#INTENT_Nav_Hotel_Inquire##
ref#d0eef7fb5d305f86_tts.wav#tts#female#7天杭州西湖武林广场店#INTENT_Nav_Hotel_Inquire#RECOG_SLOT_Hotel_Category_Literal#7天杭州西湖武林广场店
